### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by eroux**
* UserManual -> GregorioRef
 * append version to GregorioRef
 * various improvements to VersionManager

### CODE REVIEW

**Comment by eroux** [comment]
@eschwab do you want to change the version in `doc/GregorioRef.tex` (you can push in this branch directly if you want). Also, I think the date should be set by `VersionManager.py` too, what do you think?

**Comment by eschwab** [comment]
Yes, I can add the version to the titlepage. And the date too.

**Comment by eroux** [comment]
sorry @eschwab I pulled the trigger... I there are no more comments, I think it can be merged

**Comment by eschwab** [comment]
I just sat down to do it, so no problem. Looks good to me.

**Pull request merged**
