### PR TITLE
fix spurious spaces and missing %

### PR DESCRIPTION
**Pull request by eroux**
I've documented a tiny grep command allowing to spot missing `%` introducing spurious spaces in scores, please run it from time to time!

### CODE REVIEW

**Comment by rpspringuel** [comment]
I was just thinking about doing something similar the other day.  My regex-fu isn't good enough for me to check this on the fly, but I'll look this over when I get home. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
Thanks, that should be fixed

**Comment by henryso** [comment]
I take it that this doesn't affect the tests?

**Comment by eroux** [comment]
Not as much as I'd like (there really is too much space on the left of the bars, but the bug must be somewhere else...), see https://github.com/gregorio-project/gregorio-test/pull/97

**Comment by henryso** [comment]
Merging.

**Pull request merged**
