### PR TITLE
Support for arbitrary number of lines in the annotation.

### PR DESCRIPTION
**Pull request by rpspringuel**
Annotation functions are consolidated into a single function `\greannotation` which can, through multiple calls, build up an annotation with an arbitrary number of lines.
There are now two distances associated with the annotation `annotationseparation` (a renaming of `aboveinitialseparation` for consistency) and `annotationraise`.  The first controls the distance between lines in the annotation, the second raises or lowers the annotation from it's default position (baseline of the first line aligned with the top line of the staff).  This second distance should be more transparent than the old method of measuring the height of a second argument to the annotation functions and more consistent with how other spaces are manipulated.

Three tests fail, all involving the placement of an annotation (as expected, since the new default is slightly higher than the old one).

### CODE REVIEW

**Comment by rpspringuel** [comment]
No comments on this?

**Comment by henryso** [comment]
I don't feel qualified to comment on the TeX, but the documentation looks OK.

**Comment by eschwab** [comment]
I have not had the chance to test. I'll try to make time later today.

**Comment by eschwab** [comment]
Sorry for the delay. Works wonderfully. This will make #44 much easier!

**Pull request merged**
