### PR TITLE
First attempt at putting glyphs in the UCS PUA-A block.

### PR DESCRIPTION
**Pull request by henryso**
# ~~DO NOT MERGE - DOES NOT WORK~~

I tried to put the glyphs in the UCS PUA-A block to address #239 for release-3.0.

However, I ran into some problems rendering.  It seems like the wrong code points are being used by TeX.  I spot-checked values in the compiled gtex files as well as some of the values in `gregoriotex-chars.tex` and they seem to point to the right code points in the font.

If anyone has an idea what I might have missed, I would appreciate any input.

### CODE REVIEW

**Comment by eroux** [comment]
Seems fine in my example, can you be more specific about the problem you encounter? Also, what is you LuaTeX version?

By the way, you can remove `gregoriotex-chars.tex.in` and `generate-gregorio-chars.lua` in this pull request.

**Comment by eroux** [comment]
Also, I don't really understand why, but it slowed down the font generation process quite a lot... not a big deal, but I'm just surprised...

**Comment by eroux** [comment]
Also, maybe you just need to clear LuaTeX cache?

**Comment by henryso** [comment]
By way of example:

```
initial-style: 0;
%%
f.g!hwiHG'F(f.g!hwiHG'FZ)
```

produces

page

This is after clearing the luatex cache.  I'm using luatex 0.70.1, with some backported fixes, as packaged by Gentoo GNU/Linux as part of TeX Live 2012.  I'm beginning to suspect that the culprit is my relatively old version of TeX Live.  However, 2012 is the latest "stable" TeX Live in Gentoo.  This might mean that Gregorio needs a newer version of TeX Live if we put this change in.

It will take me some time to upgrade to the "unstable" TeX Live 2014 since Gentoo is a build-from-source distribution.

I too noticed the slow-down in font generation.  I don't know what's causing that either.

**Comment by eroux** [comment]
It seems so, LuaTeX of TeXLive 2015 works fine, I'll try to investigate and find the minimal working version, then outputing an error if the version is inferior...

**Comment by eroux** [comment]
It seems to be working with LuaTeX-0.76 (TeXLive 2013). I tried to test with TeXLive 2012 binary, but was unable due to other problems (in luaotfload for instance).

**Comment by henryso** [comment]
The upgrade to TeX Live 2014 does indeed make it work for me as well. Do you think TeX Live 2013 is too new a requirement for Gregorio? If not, then I think this change is merge-able.

**Comment by henryso** [comment]
Actually I still need to clean up the conversion files. I'll take care of that shortly.

**Comment by eroux** [comment]
Ok, just two more things then, sorry to bore you with that: can you add a CHANGELOG entry saying that support for TeXLive < 2013 is dropped, and add an error (in gregoriotex.lua, it's the easiest) if compiled with LuaTeX < 0.76? If the error thing is not clear to you, I'll do it.

**Comment by henryso** [comment]
I put the check in `gregoriotex.tex`.  Please review since my TeX is not really all that great.

**Comment by eroux** [comment]
The TeX seems ok to me. About the CHANGELOG, I admit I'd prefer a CHANGELOG that would just read 3.0.0, without all the rc... otherwise all major changes will be in rc1, and final release will be something like "fix bug ...", which is not that significant I believe... What do you think?

**Comment by henryso** [comment]
I don't disagree about the CHANGELOG.  However, I think it's valid to have multiple rc sections so that early adopters can keep track of what's going on and we merge them into 3.0.0 at GA.  Other developers may have other opinions, and I'd like to hear them, though.

**Comment by eroux** [comment]
Sure, we can do this change it when we release final 3.0.0. (What is "GA"?)

**Comment by henryso** [comment]
In this context, GA means General Availability (as opposed to RC = Release Candidate).

**Comment by eroux** [comment]
ok thanx!

**Pull request merged**
