### PR TITLE
update UserManual to use LuaTeX and add build script and instructions

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by henryso** [comment]
This will make building the (developer-focused) UserManual.pdf mandatory every time the application is built.  If you really think that's necessary, then fine, but I think that building the UserManual should be optional.  If there's a way to make building this a configure option, then that's probably the way to go.  If not, I think just giving the build instructions for the manual (since it's a one-liner) is good enough and will allow users to build it or not depending on their needs.

**Comment by eroux** [comment]
I don't really understant what you mean... `make` won't build the `.pdf` file, only `make dist` will do it for the tarball. Does it sound better?

**Comment by henryso** [comment]
My apologies. I misunderstood the Makefile.am.

**Comment by eroux** [comment]
Also, this commit doesn't remove the UserManual.pdf yet... Please check that the new `.tex` and build process (latexmk with some complex options) works for, you, as there might be some escaping issues in the Makefile

**Comment by rpspringuel** [comment]
See my most recent comment in #121 .

**Comment by rpspringuel** [comment]
Opps...  I meant to make that a pull request to this branch (as @henryso had done), not to push directly to it.  Hopefully no harm done.

**Comment by eroux** [comment]
Do you think it can be merged now?

**Comment by rpspringuel** [comment]
Yes, but since @henryso made modifications to `.gitignore` on another branch to do the same thing as mine here, we'll need to watch for conflicts.

**Comment by eroux** [comment]
Thanks!

**Pull request merged**
