### PR TITLE
Modified to index code point tables when needed for iteration.

### LINKED ISSUE #717: Compatibility with luaotfload 2.6
It seems Gregorio is not compatible with latest luaotfload (2.6), see [this thread](https://mail.gna.org/public/gregorio-users/2015-12/msg00036.html)

### PR DESCRIPTION
**Pull request by henryso**
Fixes #717.

Many thanks to @phi-gamma for the help.

I tested this under TeX Live 2015 with luaotfload 2.5 and luaotfload 2.6.  It passes all the tests.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by henryso** [comment]
This is updated per @eroux's comment in (outdated) henryso@38bc1d5875ec8e01371d90e32e6be76354dc6c1b.

**Comment by eroux** [comment]
Ok for me, thanks a lot!

**Comment by henryso** [comment]
@rpspringuel Would you be able to run the tests for this against TeX Live 2014?

**Comment by henryso** [comment]
Since this does work under TeX Live 2015 with either version of luaotfload, I will merge it, but it would still be good to test under TeX Live 2014 (which I currently can't do easily).

**Comment by rpspringuel** [comment]
Tested under TeXLive 2014.  Only saw the expected failures: clef_change and fix-508

**Comment by henryso** [comment]
Great, so I think this is confirmed under reasonable versions of TeX Live.

**Pull request merged**
