### PR TITLE
Implemented adjustable additional spacing for low notes.

### LINKED ISSUE #1125: Finer control on notes-text spacing
In some cases, a short `spacelinestext` should make `d` pitch considered as a low note adding space between notes and text.

See the following example

``` tex
\documentclass[11pt]{article} %%
\usepackage{fontspec} %%
\usepackage{gregoriotex} %%
\begin{document} %%

% espace au-dessus des lignes
\grechangedim{spaceabovelines}{0.429 cm plus 0.286 cm minus 0.0715 cm}{scalable}%
%the space between the lines and the bottom of the text
\grechangedim{spacelinestext}{0.32 cm}{scalable}%

\gabcsnippet{%
(c4)
Mys(e)té(gh)ri(h)um(hg) fí(h!iwjh)de(gh)i.(h) Vel:(::) Mys(e)té(gh)ri(h)um(h) fí(i)de(h)i.(h) (::Z)
<sp>R/</sp> Mor<alt>Omnes:</alt>(e)tem(g) tu(gh)am(h) an(h)nun(h)ti(h)á(h)mus,(g) Dó(h!iwj)mi(h)ne,(h) (;) et(e) tu(gh)am(h) re(h)sur(h)rec(h)ti(h)ó(h)nem(h) con(i)fi(h)té(gh)mur,(g) (,) do(hf)nec(gg) vé(e)ni(de)as.(e) (::) (g+)
}%
\end{document}
```

in which the `i` merges within the podatus. Of course this example is a bit extreme, but I think having a system similar to what's happening at the top of the staff with (`additionaltopspacealtthreshold`) would fix this issue...

### PR DESCRIPTION
**Pull request by henryso**
Fixes #1125.

Test expectations were adjusted accordingly, and a new test for the per-line count setting feature was added..

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Looks good, thanks a lot! Maybe the system to change the threshold per line could also be used for the threshold of notes above staff lines?

**Comment by henryso** [comment]
That system can be used to change *any* of the gre@space@count counts.

**Comment by henryso** [comment]
I guess I should add that to the change log.

**Comment by eroux** [comment]
Oh yes, didn't realize that! Well, you can merge, thanks a lot, that's really a big help!

**Pull request merged**
