### PR TITLE
Doc fix

### PR DESCRIPTION
**Pull request by rpspringuel**
I still need to document `\grenabccharno`, but I need to know what it does first.  That, of course, would be easier if someone who knows off hand would chime in.

Barring that, I'll try to figure it out from a detailed code inspection when I next get a free block of time (I have some homework to do for now).

### CODE REVIEW

**Comment by henryso** [comment]
`\grenabccharno` has been in from the beginning of gregoriotex-nabc.tex, but it was defined by `\newcommand`, so it wasn't caught before.  The best person to ask would be @jakubjelinek, but it simply calls (in Lua) `gregoriotex.parse_nabc`.  Looking at this function, it prints the nabc glyphs for the nabc string passed as `#1`. `#2` is the font name used as an index into nabc glyph tables, and `#3` is a scaling factor that is currently hard-coded to 1 (presumably for some future configurability?)

**Comment by rpspringuel** [comment]
Given that description, I think this function needs to be moved out of the user namespace (where it currently resides) and into the internal namespace (i.e. be renamed to `\gre@nabccharno`).  Are there objections to me making that change and documenting this function as an internal function?

**Comment by henryso** [comment]
I have no objection, but I'm also not the author of said macro.

**Comment by rpspringuel** [comment]
Pending approval from @jakubjelinek on my renaming his macro, I think this is ready for merge and then 4.2 can be released.

**Comment by rpspringuel** [comment]
I just added the last two commits necessary for release: updating the version number and consolidating the CHANGELOG entries from the betas and release candidates.  I don't have time to do anything more tonight, but assuming no objections, then my plan for tomorrow morning is to merge this PR, merge the resulting 4.2 branch into master, and build the release files.

**Comment by henryso** [comment]
No objections from me.

**Pull request merged**
