### PR TITLE
Update website and GregorioTeX LaTeX version

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by henryso** [comment]
We should also update the link on GitHub, no?

**Comment by eroux** [comment]
which one?

**Comment by henryso** [comment]
At the top of the page, where it says "source for the gregorio project 
http://home.gna.org/gregorio/".  I'm wondering if this should be changed at this time or if we should for 3.0 to release.

**Comment by eroux** [comment]
Oh, ok. We'll do this for the 3.0.0-rc1 release yes (as soon as the Mac package is done)

**Pull request merged**
