### PR TITLE
Defining small caps for PlainTeX

### PR DESCRIPTION
**Pull request by rpspringuel**

### CODE REVIEW

**Comment by henryso** [comment]
I wonder if it might just be better to issue a warning or an error if `\sc` is not defined?

**Comment by rpspringuel** [comment]
That would be more in line with what we do for `\GreUnderline`.  However, we would then need to modify the defaults styling for modes, which currently use `\sc` (and thus raise an `Undefined macro` error).

**Comment by henryso** [comment]
Do you think it would be too incoherent to have that default be different in PlainTeX ?

**Comment by rpspringuel** [comment]
It would mean that mode numbers are lowercase roman numerals by default.  Personally I think that looks odd, but it wouldn't be terribly incoherent.

**Comment by henryso** [comment]
How about using roman-majuscule as the default for the mode number system in plain TeX, then?

**Comment by rpspringuel** [comment]
That makes some sense.  I'll see what I can do about implementing that.

**Comment by rpspringuel** [comment]
Changes implemented.  No tests change.  Does anyone think I need to add tests related to this?

**Comment by henryso** [comment]
Probably a single test with a mode header is good enough, but I think a test is a good idea.

**Comment by henryso** [comment]
GregorioRef should be updated for this change, where it describes the default mode stye and where it describes the mode number system.

**Comment by rpspringuel** [comment]
Simple tests added.  Let me know if that's not enough.

**Comment by henryso** [comment]
I would add a gabc with mode header to those tests, exercising the difference in mode number system.

**Comment by rpspringuel** [comment]
Done.

**Comment by henryso** [comment]
Looks good.

**Pull request merged**
