### PR TITLE
fixes #1034

### LINKED ISSUE #1034: manual final custo not correctly spaced
See

```tex
\documentclass[12pt]{book}
\usepackage{geometry}
\geometry{a5paper}
\usepackage{fontspec}
\usepackage{gregoriotex}
\gresetlastline{justified}
\begin{document}

\gabcsnippet[0]{(c4) (f) (gh) (h) (h) (h) (hr) (hr) (hr[ev:\hfill]) (hg) (ixgi) (h) (hr[ocba:1;7.5mm]) (hg) (gh) (;z) (f) (gh) (h) (h) (h) (hr) (hr) (hr[ev:\hfill]) (hg) (ixgi) (h) (hr[ocba:1;7.5mm]) (hg) (gh) (;//h+)}

\end{document}
```

in which the spacings at the end of the two lines are different.

### PR DESCRIPTION
**Pull request by eroux**
fixes #1034

### CODE REVIEW

**Comment by henryso** [comment]
Which tests evidence the fix?  Perhaps you should add the example from the #1034?

**Comment by eroux** [comment]
well, testing more, I discovered a small bug, leading to a less small bug, etc. now things start to get quite messy, let's not merge it now...

**Comment by eroux** [comment]
I think it's ready, please review

**Comment by henryso** [comment]
Mechanically, this looks good to me, but it would be nice if @rpspringuel can check as well.

**Comment by rpspringuel** [comment]
I've run the tests and can confirm everything passes.  Looking at a few of the changed/new results, I think this is good to go (though I do not have time to check them all right now).

**Comment by henryso** [comment]
OK, I'll merge.  Thanks.

**Pull request merged**
