### PR TITLE
Gabc Documenation

### PR DESCRIPTION
**Pull request by henryso**
I took a stab at adding GABC documentation to GregorioRef ~~since no one else seemed to want to start it~~.  I've pushed this directly to the main repository in its own branch so we can all collaborate on getting this section into better shape.

Please take a look and either add what you think I've missed or let me know what I've forgotten to put in and I try to add it.

### CODE REVIEW

**Comment by rpspringuel** [comment]
You got much more ambitious with your start than I did.  It's going to take me a while to proofread everything.

One thing I do notice, is that this PR is against `develop`.  I think we should base the gabc documentation effort against `release-5.0` with a daughter branch which pulls in `develop` and documents the gabc syntax which will be new in 5.1 (dotted barlines, for the moment).  It would be highly useful to upload a pure documentation change to CTAN for those aspects of gabc notation which are already in the version loaded there (the 5.0 series).

**Comment by henryso** [comment]
I can do that, but this documentation has been this way for so long that I think we might as well cut a 5.1 soon with the new enhancements and the documentation.  It's almost time for TeX Live 2018, and we cut it pretty close last time.

**Comment by rpspringuel** [comment]
The pretest for TeXLive is usually at the start of April.  Admittedly, we did cut it really close (and perhaps just a bit over) last year, so we should plan on being ready early, but it's still a solid 4 months away.  Unless this documentation process really drags through the end of the year, I expect to be cutting 5.0.4 for CTAN at about the same time that we cut 5.1.0 (which, I agree, should be soon).

**Comment by henryso** [comment]
There's actually two things that would need to be taken out.  Let's try to wrap up the review and update in this branch for the 5.1.0 documentation relatively quickly.  Then I'll grab a copy of the Gabc.tex file, re-base this branch, adjust it to take out the 5.1.0 specific things and re-pull it against release-5.0 if that still makes sense when the time comes.

Note: I will be away for a good deal of December and, though I will have internet and all that fun stuff, I can't say how much time I will be able to spend on this.

**Comment by rpspringuel** [comment]
Well, let's make this as quick as possible then.

I do have to say I'm not happy with the topic order/organization at this point (and I realize that's not your fault, as you're borrowing most of it from the website).  I have some ideas for what might make more sense, but need a bit of time to flesh them out.  Hopefully I'll have something later today that others can comment on.

**Comment by rpspringuel** [comment]
Please look at https://github.com/gregorio-project/gregorio-project.github.io/pull/67/commits/610593acb3301c322187dfcb32ba67d4fea57e99 for the start of my ideas on restructuring.

**Comment by rpspringuel** [comment]
You know, that js file isn't all that easy on the eyes so I just committed an attempt to make that structure concrete, at least for the first part of the gabc documentation.  I haven't touched the note syntax yet (except to extract those elements which I'm moving into one of the earlier sections).  This should be easier for people to study and comment on.

**Comment by rpspringuel** [comment]
I don't think this is done, but I'm going to suggest merging this immediately and making a release so that we're ready for the TeXLive pretest.  We can come back to adding to the docs after we've prepped everything for TeXLive 2018.

**Comment by henryso** [comment]
I agree.  Merge it when you're ready.

**Pull request merged**
