### PR TITLE
Protect filenames

### PR DESCRIPTION
**Pull request by rpspringuel**
I've created a function for protecting file names (substituting `-` for a bunch of invalid characters) and used it to protect snippet related files.  This prevents projects which have these characters in the main project file's name from not finding the executable (#1416).

### CODE REVIEW

**Comment by rpspringuel** [comment]
Just realized that I haven't created a test for this issue.  I'll work on that later today.

**Comment by rpspringuel** [comment]
Problem with creating a possible test.  Adding a single quote to a file name raises the following error from the testing script: `gxargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option`

@henryso do you have any suggestions for how we might deal with this in the script?

**Comment by rpspringuel** [comment]
I've been thinking about this and since the problem is in trying to mix this unusual filename with `xargs` perhaps we should run this test without the benefit of `xargs`?  Perhaps as an optional "extra" at the end?

**Comment by henryso** [comment]
Perhaps the harness can be rewritten to use the null separator so that `-0` can work.  I haven't thought about how difficult that would be to do, though.

**Comment by henryso** [comment]
I think I've figured out a way to make this work.  However, I think it will require a change to the viewer settings in gregorio-test.rc.  Also, it'll take a bit more doing before I'm done.

**Comment by henryso** [comment]
I have something that works, but I'd like to wait for #1429 to be merged so that it's easier to make the changes I need to make to `harness.sh`.

**Comment by henryso** [comment]
On second thought, looks like I'd need to get this against the ctan branch.  I'll try to rework it tomorrow.

**Comment by henryso** [comment]
I slept on it and decided I could just bring the changes in wholesale.  @rpspringuel Please try your tests with this code, and merge gregorio-project/gregorio-test#328 if it is satisfactory or provide feedback for me to fix.

**Comment by henryso** [comment]
This PR is getting a bit difficult for me to follow, but I think as long as the tests work (which they seem to do) and this change works on Windows as well, then we're good to go ahead with it.

**Comment by rpspringuel** [comment]
This PR is the one that would be closed without merging.  #1450 is I think a simpler and therefore better fix. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henryso** [comment]
OK, I'll put my comment there.

**Pull request closed without merging**
