### PR TITLE
Log gregorio messages

### PR DESCRIPTION
**Pull request by henryso**
The idea was noted in https://github.com/gregorio-project/gregorio/issues/1023#issuecomment-194902969

Since it appears we don't need further implementation on #1023, I am submitting this as its own pull request.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Looks good, thanks! Did you test it in an unfriendly environment by tuning some kpse restrictions? It would work, it's just in case...

**Comment by henryso** [comment]
It works fine for normal scores.  I use the same filename transformation (but using `.glog` instead of `.gtex`), so if kpathsea allows write to the `.gtex` file, it should allow write to the `.glog` file.

Snippets, on the other hand, pose a problem.  We use `os.tmpname()` to get a filename for writing the gabc from the snippet.  LuaTeX allows this, and the "read anything" typical permission for kpathsea will allow these to be read.  The current implementation (in this pull request) also uses `os.tmpname()` to get a filename for the log file.  However, the kpathsea inside the gregorio executable will reject a write to this file.

Should I disable the logging when using snippets?

**Comment by henryso** [comment]
I think I've come up with a workaround.  I'll try to prepare it tonight.

**Comment by henryso** [comment]
This version works on a restricted kpathsea environment unless read access is too limited to load the gregorio package.

**Comment by eroux** [comment]
Thanks!

**Pull request merged**
