### PR TITLE
Added support for Dominican-style neumes.

### PR DESCRIPTION
**Pull request by henryso**
Implements #1.

This is a bit rough, but it works.  I still have a lot of testing to do before this can be merged, but please advise me if you notice anything I should do here.

### CODE REVIEW

**Comment by eroux** [comment]
Seems good to me, but I'm in no position to judge properly...

**Comment by henryso** [comment]
I've run into an issue while testing. A note at `d` typically doesn't have a long queue (unlike most notes which are on lines), but with the `dV>` figure in its Dominican form with inverted stem, it runs into the line.  I think I can do something with a new TeX command for this particular case, but if anyone has any other ideas, I'm all ears.

**Comment by henryso** [comment]
As far as this change goes, I think this is ready for a final review/merge.  If someone familiar with Dominican glyph usage comes forward, we can address their concerns at that time.

**Comment by eroux** [comment]
ok for me!

**Comment by henryso** [comment]
Hearing nothing to the contrary, I'll merge this.

**Pull request merged**
