### PR TITLE
document removal of Vbarsmall, greletterbar and greletteraltbar

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by henryso** [comment]
I just noticed that *4.0* is bigger than *3.0*.  Is that the style we are adopting, the current release larger than the prior releases?

**Comment by eroux** [comment]
I don't really understand your question...?

**Comment by henryso** [comment]
If you look at `UPGRADE.md`, 4.0 has `#` and 3.0 has `##`, so the output makes 4.0 look bigger than 3.0.

**Comment by eroux** [comment]
Oh, sorry, my mistake, fixing this

**Comment by henryso** [comment]
Looks good to me.

**Pull request merged**
