### PR TITLE
Latest fixes for TeX Live integration.

### PR DESCRIPTION
**Pull request by henryso**
Fixes issues found by Peter Breitenlohner and Akira Kakuto from the TeX Live team.  For #551.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by henryso** [comment]
Ok, now gregorio-resources.o is dependent on both gregorio-resources.rc and gregorio.ico, and both are in the tarball.  I think this is done.

**Comment by henryso** [comment]
I left the PIC warning unfixed.

**Comment by eroux** [comment]
Thanks a lot! Do you think the warnings of MSVC (const argument different between definitions) are worth fixing (I have no strong opinion about that)?

**Comment by henryso** [comment]
The differences reflect interface vs implementation details, which is why GCC (or clang for that matter) doesn't flag these things.  It shouldn't matter to the caller if I modify the variable containing a value passed (prevented by `char *const`), but it does matter if I modify something that has a side effect (prevented by `const char *`).  Therefore, my opinion is to leave them alone and ask Akira Kakuto to use the `-wd4028` option.

**Comment by eroux** [comment]
ok!

**Pull request merged**
