### PR TITLE
Updating contrib/ directory

### PR DESCRIPTION
**Pull request by eroux**
README -> README.md
removing outdated gabc.lang (incompatible with GtkSourceView 3)
replace gregorio-mode.el by a reference to the repository
remove doc for deprecated engines

### CODE REVIEW

**Comment by rpspringuel** [comment]
Looks good, but my internet problems are still with me this morning so I can't test.

**Comment by eschwab** [comment]
Does `gabc.lang` need to go back into the makefile? Other wise looks fine.

**Comment by eroux** [comment]
Indeed, sorry!

**Comment by eroux** [comment]
done

**Pull request merged**
