### PR TITLE
Added case to handle horizontal episema over salicus.

### LINKED ISSUE #511: Horizontal episema over salicus doesn't render correctly.
This comes from Sr. M. Ruth OSB of Abbazia Mater Ecclesiae via the gregorio-user list.

this gabc:
```
name: Salicus episemato;
initial-style: 0;
%%
(c4) fhOj___(fhOj___) (::) f_hOj(f_hOj) (::) fhO__j(fhO__j) (::)
```
in Gregorio 3.0 produces:
image

The `develop` branch produces something slightly different, but still wrong:
image

### PR DESCRIPTION
**Pull request by henryso**
Fixes #511 for Gregorio 3.0.

Please review.

### CODE REVIEW

**Comment by eroux** [comment]
ok

**Comment by henryso** [comment]
I suggest holding off on the merge of this until we're ready to release 3.0.3 so as not to pollute `master`.

**Comment by rpspringuel** [comment]
If there are no objections, I say we release this patch at the end of this week.

@henryso, can you increment the version number on this branch to prepare for that?

**Comment by henryso** [comment]
When I did this on my computer (not committed yet), it put today's date on it.  Is that OK?

**Comment by rpspringuel** [comment]
It's okay by me.

**Comment by henryso** [comment]
I updated the version number and change log entry.

**Pull request merged**
