### PR TITLE
#1182: new spaces

### PR DESCRIPTION
**Pull request by eroux**
Spaces from the Antiphonale Monasticum project

### CODE REVIEW

**Comment by henryso** [comment]
As one who is aesthetically challenged, I cannot really speak to the "beauty" of these spaces, but I will ask if we should really be changing them this late in 4.2.

**Comment by eroux** [comment]
As you prefer, another option is to send them to the list and make them the default only starting from 5.0... what do you think?

**Comment by henryso** [comment]
I would certainly feel more comfortable doing that.

**Comment by henryso** [comment]
@eroux Perhaps we should send this to the list now and make the changes in 5.0?

**Comment by eroux** [comment]
Yes, I'm just waiting a few days for a better version of the spaces

**Pull request closed without merging**
