### PR TITLE
Miktex

### PR DESCRIPTION
**Pull request by rpspringuel**
The installer is now compatible with MiKTeX.

Still need documentation before merging.

Also, need to update version number.  I think this is probably a bugfix version, but am willing to hear arguments to the contrary.

### CODE REVIEW

**Comment by henryso** [comment]
If by "bugfix" version, you mean what http://semver.org/ calls PATCH, then I agree. bump the third number.

**Comment by rpspringuel** [comment]
Yes.  That's what I meant.  Sorry about the terminology confusion.

**Comment by eroux** [comment]
Fine for me!

**Comment by rpspringuel** [comment]
Other than the notation in the CHANGELOG, is there any other documentation you think this needs?

**Comment by eroux** [comment]
I don't think so...

**Pull request merged**
