### PR TITLE
Gsp default

### PR DESCRIPTION
**Pull request by rpspringuel**
Addresses underlying cause of #1460 

This PR moves `gsp-default.tex` to be an internal file.  This allows for us to version check it to make sure we're loading one which properly defines all needed distances and penalties.  As part of this `\grecreatedim` is moved to the internal namespace as `\gre@createdim`.

`gsp-sample.tex` is now provided in the doc folder as an example space configuration.  Right now it's simply a duplicate of `gsp-default.tex` except for the following:

1) It has no version check (version checking is only for internal files)
2) It uses `\grechangedim` (an User macro) instead of `\gre@createdim` (an internal macro)
3) The comments have been edited to make them slightly more user friendly (please double check these)

### CODE REVIEW

**Comment by rpspringuel** [comment]
Oh, I should note here:  **This is a user interface change and warrants a bump in the major version number when released.**

**Comment by henryso** [comment]
If this will be an internal file, maybe it should get a name change as well?  `gregoriotex-sp-default.tex` perhaps?

**Comment by rpspringuel** [comment]
That'll make it harder for people to reload the defaults after changing to a custom space.  As is `\greloadspaceconf{default}` will reload the default spacing configurations, if we change the name, then that won't work.

Oh... That does make me realize something though, because rescaling is handled within `\grechangedim` (which is not used in `gsp-default.tex`) we're going to run into a scaling problem when reloading the defaults if the current staff size is not 17.  I'm going to need to add some special handling for loading the defaults to account for that.

Now that I think about it, I guess that makes it relatively easy to change the name.  If there's already some special handling of the defaults, that special handling can be extended to the file name too.

**Comment by henryso** [comment]
I merged the test by accident, so I'm going to merge this as well.  The name change bit can be a separate pull request.

**Pull request merged**
