### PR TITLE
Added support for descending pes oriscus (renamed from virga strata).

### LINKED ISSUE #1272: (efO e) pointing in the wrong direction (?)
With latest gregorio, if I try

```tex
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gabcsnippet{(c4) f(efO e)}
\end{document}
```

I get

bug

while Solesmes would like the oriscus to point to the following note (down)

### PR DESCRIPTION
**Pull request by henryso**
Fixes #1272.

I added the requested figures to the tests, but since I took this opportunity to rename some of the glyphs and symbols, some of the other expectations also changed.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Looks good to me, thanks! I'm wondering if `0` and `1` can be applied to `efO`? There's not test about that... If it doesn't I think it would be a good idea to add it, but it can be in another request

**Comment by henryso** [comment]
`0` and `1` *can* be applied to any `o` and `O`.  I'll add the test.

**Comment by henryso** [comment]
The requested tests have been added.  Please review.

**Comment by eroux** [comment]
Looks perfect, thanks!

**Pull request merged**
