### PR TITLE
Moved install logic from fonts/Makefile to install-gtex.sh. Fixes #97

### LINKED ISSUE #97: Should "install" from the fonts Makefile depend on the fonts?
Currently, the .ttf fonts are built from the .sfd files in the fonts directory and then are committed into the repository.  This is fine because only someone working on the fonts would be modifying them.  That person would then presumably commit the generated fonts.

However, if someone clones the repository from scratch, chances are the time stamps on the .sfd files will be the same or newer than the timestamps on the .ttf files.  Someone running make install just to install the files into their TeX directory will then be forced to rebuild the .ttf files.  It also means that the person installing Gregorio must have python, fontforge, and the python fontforge bindings.

The cleaner solution would be to have two Makefiles.  One in the fonts directory, whose only purpose is to make fonts, and one in some other directory, whose purpose is to install the GregorioTeX files.  This latter Makefile would fail if, for some reason, the .ttf files are missing, but it would not try to rebuild them at that point.

Alternately, we can rejig the current fonts Makefile to have two targets: one for creating fonts and one for installing GregorioTeX.  This gets a bit messy (and is why I say the previous is cleaner) because the "make the fonts" target needs the sfd-to-ttf dependency while the "install" target must not have it lest the fonts be rebuilt unnecessarily.

I suppose there is a third option: add `touch *.ttf` after `cd fonts` in the installation instructions to be sure they have a later timestamp than the .sfd files.

I can make the Makefile changes and submit a pull request once we decide if/how we want to handle this.

### PR DESCRIPTION
**Pull request by henryso**
See older comments in https://github.com/gregorio-project/gregorio/pull/96

### CODE REVIEW

**Comment by rpspringuel** [comment]
I like @eroux's comment from the previous thread:

> maybe it would be easier if there was a --local and --global option that would be shortcuts for var:TEXMFHOME and var:TEMFLOCAL? That would ease the invocation for most users...

I find using `--local` in a way that doesn't map onto `TEXMFLOCAL` confusing though, so I might use option names like `--home` and `--local` or `--user` and `--system` or even `--me` and `--everyone`.

**Comment by henryso** [comment]
I was about to comment on having the same concerns about using the word local.  I was going to suggest system-wide and personal, but I like your suggestion of user and system much better.  I also see no need to have the dashes.  The syntax would be:

```
install-gtex.sh system
```

and 

```
install-gtex.sh user
```

I will push these changes shortly.

**Comment by eroux** [comment]
Just a final request if I may, can you please add -j* (or even replace --jobs=* by -j*)? Also, I wanted to add some [hardening flags](http://security.stackexchange.com/questions/24444/what-is-the-most-hardened-set-of-options-for-gcc-compiling-c-c) in the build script, but that can be for later...

**Comment by henryso** [comment]
I made it take `-j<N>` in addition to `--jobs=<N>`, but I can't make it accept `-j <N>` (with a space) without an overhaul to the existing option parsing logic.

**Comment by eroux** [comment]
It's perfect, that's the way it's usually called with make

**Comment by eroux** [comment]
I need to apply

```
diff --git a/install.sh b/install.sh
index d2fed79..d203378 100755
--- a/install.sh
+++ b/install.sh
@@ -18,7 +18,7 @@ make install || die "install Gregorio"
 echo
 
 echo "Installing GregorioTeX"
-install-gtex.sh "${1:-system}" || die "install GregorioTeX"
+./install-gtex.sh "${1:-system}" || die "install GregorioTeX"
 echo
 
 echo "Installation complete."
```

before being able to `./install.sh`, can you please apply it (if it works on your system)?

**Comment by henryso** [comment]
Serves me right for having "." in my PATH.  Fixed.  Thanks for finding it.

**Pull request merged**
