### PR TITLE
Suppressed \GreLastOfScore if only no-element syllables follow it.

### LINKED ISSUE #1205: problems when final syllable has no notes
The following example:

```
\documentclass[a5paper, 12pt]{book}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gresetinitiallines{0}
\gabcsnippet{(c4) Ma(i)rí(kko>)a!(j.) R(::) Salve Mater.()}
\end{document}
```

produces the strange result:

buggregorio

I think this is because of the way `\GreLastOfScore` is handled...

### PR DESCRIPTION
**Pull request by henryso**
Fixes #1205.

I'm still unsure if this causes a problem related to #1116.  @rpspringuel Would you be able to check?

No tests break, and I added the test from the issue.

Other than that, please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Looks good to me, thanks a lot!

**Comment by rpspringuel** [comment]
I'm not sure what you're concerned about, but will take a look at the results later.  @henryso, if you could elaborate on what you're worried about, I'll have a better idea of what to look for.

**Comment by henryso** [comment]
In rpspringuel/gregorio#5, I moved `\GreLastOfScore` to its position prior to this pull request.  That was either part of the fix for #1110 itself or the issue you identified in #1116.

**Comment by rpspringuel** [comment]
Well, the problem I identified in #1116 has to do with discretionaries mid-score, so this won't effect that (as evidenced by the fact that the clef-change test doesn't change).  As for #1110, there is a test for that now and it looks good too, so I don't see any problems.  All tests pass and the new test result looks good.

**Comment by henryso** [comment]
Ok, then I guess this is good to merge.  Thanks!

**Pull request merged**
