### PR TITLE
Fix #404 + reenable warnings

### LINKED ISSUE #404: bottom brace for bars?
Page 300 (last line) of Graduale Triplex, there is something that cannot be represented in gabc yet: a round brace beneath a bar. Maybe `_0` could represent it?

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by eroux** [comment]
@henryso I'll let you fix the warnings as they're your new code, but 90% are about defined but not used variables or functions, so it's harmless... only one would really need fix, it's parenthesis missing in a conditional

**Comment by henryso** [comment]
@eroux Please review #407 and merge into this branch if satisfactory.

**Comment by eroux** [comment]
I think this could be merged now?

**Comment by henryso** [comment]
Tests pass.  Let's merge.  I will add a test for underbrace shortly as well.

**Comment by henryso** [comment]
Is the underbrace change supposed to handle `(g,_0h)` ?

**Comment by eroux** [comment]
no, it was a mistake of mine in the initial issue, but the overbrace/underbrace corresponds better to the desired output than barbrace

**Pull request merged**
