### PR TITLE
Ctan

### PR DESCRIPTION
**Pull request by rpspringuel**
PR showing what #1209 would do.

### CODE REVIEW

**Comment by henryso** [comment]
It's hard to review this because most of the file changes are copyright dates and version bumping, but these have all be reviewed elsewhere, so as long as the tests look OK, I think this is good.

**Comment by eroux** [comment]
ok for me too

**Comment by rpspringuel** [comment]
Since I don't have the time to take care of this today (Sunday), on Monday I'll merge this and publish the release.  I'll also prepare a new release candidate for 4.2 at the same time so that we can get people to test the installer changes there.

**Comment by anthonyfok** [comment]
Hi @rpspringuel, thank you so much for merging #1201.  But, if it is at all possible, please "stop the press!" and wait just a little bit longer (say an hour or two?) before you actually release 4.1.5: I found a bug in my code, in that when `\setmainjfont` is used to set the Chinese/Japanese font, the user is likely to run into this crash:

```
! error:  (node lib): lua <node> expected, not an object with type nil
```

For example, "Adobe Ming Std" and "AR PL UKai TW" work fine, but STZhongSong, Fandol, cwTeXKai etc. would crash... for some reasons, with some fonts, the glyph node isn't found within the hbox, but instead one level deeper.

I have a 3-line, patch, not perfect, but at least no more crashing.

I will write more at #1180 or #1201.

Thanks again!

**Pull request merged**
