### PR TITLE
Added MetaPost rendering of braces.

### PR DESCRIPTION
**Pull request by henryso**
Implements #535.

While testing, I found and fixed an issue with multiple scores inclusions and variably-sized braces.  The fix uses a `\directlua` call to generate the `\luatexlatelua` command with the score identifier carved in so that it will be correct on ship out.

This is ready for review and critique, especially on the look of the braces as they change size.  They should be very close to the greciliae figures when at their design widths but change in various, non-linear ways as they stretch out in an attempt to keep horizontal line weight more-or-less the same throughout the range of widths.

### CODE REVIEW

**Comment by eroux** [comment]
Patch looks good, can you post a picture showing the curly braces at different widths?

**Comment by henryso** [comment]
image

**Comment by henryso** [comment]
Generating that image caused me to think further about the tuning of compressed round braces (not much I can do for curly braces, though).  Here are the salient parts of the image (still at 300 dpi):
image

**Comment by eroux** [comment]
Ok for me to merge!

**Pull request merged**
