### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by avbop**
Just a few typos I noticed in some of the READMEs.

### CODE REVIEW

**Comment by rpspringuel** [comment]
These changes are acceptable to me.  Thanks for the proofreading help.

**Comment by henryso** [comment]
Should we merge this directly into master?

**Comment by rpspringuel** [comment]
Given that it's purely in the documentation, I don't have a problem with it per se, but I think our policies would indicate that this should be merged into release-5.0 (and develop) and only pushed to master when we make another release.

**Comment by henryso** [comment]
Ok, I will re-pull it against release-5.0.

**Pull request closed without merging**
