### PR TITLE
Add --with-kpathsea to configure to check against openin_any and openout_any

### PR DESCRIPTION
**Pull request by eroux**
I think this could be merged, this is a costless improvement. @jperon you might be interested in that.

### CODE REVIEW

**Comment by eroux** [comment]
no comment?

**Comment by henryso** [comment]
I can't comment on the Debian bits.  I haven't had time yet to try out the C changes.

**Comment by jperon** [comment]
I just tested `build-deb.sh --git` on debian (sid), after installing `libkpathsea-dev` ; it builds and installs like a charm. Nevertheless, when I tried to build source package and uploading it to [my testing ppa](https://launchpad.net/~cataclop/+archive/ubuntu/gregorio-test), it [failed](https://launchpadlibrarian.net/206694995/buildlog_ubuntu-wily-amd64.gregorio_3.0.0%2Bgit20150517%2B9914e2a-1_BUILDING.txt.gz) to build.

**Comment by henryso** [comment]
As far as the C changes go, they (and work) fine to me.

**Comment by eroux** [comment]
@jperon the error you get is weird:

    checking for stdint.h... (cached) yes
    ./configure: line 5172: syntax error near unexpected token `KPSE,'
    ./configure: line 5172: `   PKG_CHECK_MODULES(KPSE, kpathsea,'
    ==> config.log <==
    This file contains any messages produced by compilers while
    running configure, to aid debugging if configure makes a mistake.

during configure... I really don't know how to debug this... What are the steps to reproduce it?

**Comment by eroux** [comment]
@henryso ok great, this means that gentoo is providing kpathsea as a shared library... If I understand Gentoo correctly, this means that everything needed to build against kpathsea is provided when you install any TeXlive binary?

@eschwab what about arch?

**Comment by jperon** [comment]
@eroux To reproduce, under Debian : 

    ./build-deb.sh --fullname='NAME' --email='YOUR@EMAIL' --version='devel' --git --source
    dput PPA-GREGORIO build/gregorio*.changes

with PPA-GREGORIO being configured well in your `~/.dput.cf`

**Comment by jperon** [comment]
The problem is that I get this error only by uploading on ppa. If you like it, I could test a build within an ubuntu docker container, to see wether I get the same error.

**Comment by eroux** [comment]
It would help indeed, maybe ubuntu still has `libkpathsea5` instead of 6? But the error message doesn't really talk about that... Maybe it's the autotools version?

**Comment by henryso** [comment]
@eroux actually, I was just testing the changes to the clobber code and not kpathsea per se.  If I configure with `--with-kpathsea` on Gentoo, I get
```
configure: error: Package requirements (kpathsea) were not met:

No package 'kpathsea' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

While there is a libkpathsea.so.6.2.0 and kpathsea.h, Gentoo does not appear to provide a `kpathsea.pc` file for pkg-config.

I can compile it with kpathsea by using
```
KPSE_CFLAGS='-I/usr/include' KPSE_LIBS='-L/usr/lib64 -lkpathsea' ./configure --with-kpathsea
```

And then it does appear to stop me from writing files using absolute paths.

**Comment by eroux** [comment]
Ok, I'm affraid hand-writing `KPSE_CFLAGS` and `KPSE_LIBS` will be the canonical way of compiling gregorio under some systems... Maybe you could bugreport against the Gentoo TeXlive package for the missing `kpathsea.pc` file?

@jperon the first compilation of your Docker file takes quite long, but if you add `pkg-config` to the packages to install, it should work

**Comment by jperon** [comment]
Perhaps `pkg-config` should be added to `Build-Depends` then : I'm able to tell `docker` what I want it to install, but I can't tell `launchpad` the same thing !

**Comment by eroux** [comment]
@jperon that was aded in https://github.com/gregorio-project/gregorio/commit/c1682389980acc962304d5d5d00c5cf0e8c9a2a5

**Comment by henryso** [comment]
Is it possible in autotools to first try pkg-config, and then, if that fails, attempt to see if just adding `-lkpathsea` will work before enabling it?

**Comment by eroux** [comment]
Yes, that might be a solution... having only `-lkpathsea` in `KPSE_LIBS` (like under Debian) works for you?

**Comment by henryso** [comment]
Yes, the library and its include files are in the standard library and and include directories, so no `-I` or `-L` arguments are necessary.

**Comment by jperon** [comment]
I've just tested upload to ppa : it works from c168238.

**Comment by eroux** [comment]
@henryso can you test the current state? If pkg-config fails to spot kpathsea, it should try `-lkpathsea`...

**Comment by henryso** [comment]
@eroux It seems to work fine here.

**Comment by jakubjelinek** [comment]
If libkpathsea keeps changing the SONAME often (every year?), but the needed function is always called the same and has the same argument types/return values, there is always the option to add a fallback code that will just dlopen ("libkpathsea.so.6", RTLD_LAZY); (and similarly try so.5, so.7 etc.) and dlsym the one or two needed symbols from there.  You could then say you support everything from TeXlive 2013 to 2016 or similar.

**Comment by henryso** [comment]
For my own curiosity, we are using the kpathsea library in order to be compliant with what?  Can someone point me at some documentation?

**Comment by eschwab** [comment]
Everything build fine for me. I use TeXLive directly from Tug/CTAN so I have full control over the packages installed. I also checked the arch `texlive-bin` package and it does include kpathsea, so most arch users should be fine.

**Comment by eroux** [comment]
@henryso the kpathsea library allows to check if input and output files comply with the `openout_any` `openin_any` settings (no absolute path, no file starting with a dot, input and output file in a subdir of the current dir. There is no real documentation for that sadly... some comments in texmf.cnf are all I've found.

@jakubjelinek, TeXLive doesn't officially provide kpathsea as a shared library, only some Linux distributions provide it, so any distribution can provide any soname, unrelated to the others...

**Comment by eroux** [comment]
@henryso : completing my previous comment, we comply with it in order to be able to put gregorio in the `shell_escape_commands` settings of default `texmf.cnf` provided by TeXLive, so that users don't have to use `lualatex --shell-escape`, it will simplify the installation and configuration process...

**Comment by eroux** [comment]
@jperon I changed the Debian things a bit, can you just make a final test before this gets merged?

**Comment by rpspringuel** [comment]
This is breaking my ability to build.  I get the following error when I try:

> ./configure: line 5173: syntax error near unexpected token `KPSE,'
> ./configure: line 5173: `    PKG_CHECK_MODULES(KPSE, kpathsea,'

Adding or removing the `--with-kpathsea` option doesn't make a difference, the error results either way.

**Comment by eroux** [comment]
I think you're lacking `pkg-config`, though it shouldn't even try to use it if you don't specify `--with-kpathsea`... Can you just try with latest commit?

**Comment by rpspringuel** [comment]
Still failing, but now with what looks like an unrelated error:

> gabc/gabc-score-determination.l:30:10: fatal error: 
>       'gabc-score-determination-y.h' file not found
> #include "gabc-score-determination-y.h"

Presumably this means I've got some issue with the generated files not being generated properly.  Unfortunately applying `make maintainer-clean` and then `./build.sh --arch=x86_64 --force=autoreconf` isn't fixing this.  Any hints as to how to make this work are appreciated.

I don't have time right now, but I'll test from within my clean test environment later (maybe tomorrow).

**Comment by eroux** [comment]
I've run into that too (but I can't reproduce it now)... I admit I don't really understand what's going on, as make should know how to generate `gabc-score-determination-y.h`... This is a bit mysterious to me... I'll inspect that tomorrow, but I don't think it's related to this PR specifically. Can you try 

    make src/gabc/gabc-score-determination-y.h

and then make again?

**Comment by jperon** [comment]
As of a2eda08, compilation on ppa [fails](https://launchpadlibrarian.net/206778341/buildlog_ubuntu-wily-i386.gregorio_3.0.0%2Bgit20150518%2Ba2eda08-1_BUILDING.txt.gz).

**Comment by eroux** [comment]
@jperon thanks for your test! Can you make another one with latest commit please? (sorry for the trouble)

**Comment by jperon** [comment]
Last build succeeded !

**Comment by eroux** [comment]
Ok, so the only bug left is the one of @rpspringuel ... I'll try to see how to debug this kind of Makefile maze... @jakubjelinek do you have some experience with Makefile intricate cross-dependencies?

**Comment by henryso** [comment]
I started a bit of research on this. I don't know if it's related, but the bison and one of the flex invocations produces two files.  Apparently the only way to have GNU make handle multiple outputs is with a % wildcard rule (`%.c %.h: %.y`) of some sort.  The way we currently do it is a hacky way that tells make that the .h file is based the the .c file produced by the .y or .l file.  This has the deficiency of not recreating the .h if if it is deleted but the .c file left behind.

**Comment by eroux** [comment]
I can't test right now, but in our case maybe `%-l.c %-l.h: %.l` and `%-y.c %-y.h: %.y` would work?

**Comment by henryso** [comment]
Our case is a little more complex than that because only one of our .l files produces a .h file.  Also, the current rules have been in place for a while now, and @rpspringuel has not had problems with it until now.  So I'm not sure it'll actually solve any problem, but it certainly is worth trying in case it does.

**Comment by eroux** [comment]
Should be working now... @rpspringuel (and everyone) can you please test?

**Comment by henryso** [comment]
It doesn't work.  See my comment on 626e861155c3ba6eb0a3e98e17ad48774efa7a05.

**Comment by eroux** [comment]
Right, thanks a lot! I've documented it, as it's easily forgettable...

**Comment by henryso** [comment]
Something was still bothering me about this, so I studied the code a bit more.

`gabc-score-determination-y.c` includes `gabc-score-determination-l.h` and `gabc-score-determination-l.c` includes `gabc-score-determination-y.h`.  Therefore it is possible, if the rules are executed (by make) in a slightly different order, that one or the other header file will be missing when compiling the .o files.  To solve this, we really need to somehow tell make that the .o depends on the .h rather than the .c depending on the .h.

**Comment by eroux** [comment]
ok, reverted my mistake

**Comment by henryso** [comment]
I actually don't think those .o rules are doing anything, and you were right to remove them (which is why I didn't comment on them before).  The .o files have a "gregorio-" prefix.  In looking at the automake manuals online, it seems that using `BUILT_SOURCES` might be the right thing to do, but since these are maintainer-built sources that we don't need typical users to recompile, I have to study it a bit more.

**Comment by eroux** [comment]
Indeed, I've never used `BUILT_SOURCES` but it seems right... It seems to be [advised](http://www.gnu.org/software/automake/manual/html_node/Yacc-and-Lex.html)

**Comment by rpspringuel** [comment]
@eroux when I try `make src/gabc/gabc-score-determination-y.h` on the latest commit I get an error: `No rule to make target`.

**Comment by eroux** [comment]
That's a bit weird... did you run `autoreconf -f -i` and `./configure` before? Anyway, this shouldn't be needed anymore. What does just `make` say?

**Comment by rpspringuel** [comment]
I tried a full cycle:

```
make maintainer-clean
Making maintainer-clean in src
 cd .. && /opt/local/bin/bash /Users/RPS/Documents/Programming/gregorio/build-aux/missing automake-1.15 --foreign src/Makefile
 cd .. && /opt/local/bin/bash ./config.status src/Makefile depfiles
config.status: creating src/Makefile
config.status: executing depfiles commands
test -z "gregorio" || rm -f gregorio
rm -f *.o
rm -f ../windows/*.o
rm -f dump/*.o
rm -f gabc/*.o
rm -f gregoriotex/*.o
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f ../windows/.deps/.dirstamp
rm -f ../windows/.dirstamp
rm -f dump/.deps/.dirstamp
rm -f dump/.dirstamp
rm -f gabc/.deps/.dirstamp
rm -f gabc/.dirstamp
rm -f gregoriotex/.deps/.dirstamp
rm -f gregoriotex/.dirstamp
rm -f config_.h stamp-h1
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
test -z "gabc/gabc-score-determination-l.c gabc/gabc-notes-determination-l.c gabc/gabc-score-determination-l.h gabc/gabc-score-determination-y.c gabc/gabc-score-determination-y.h" || rm -f gabc/gabc-score-determination-l.c gabc/gabc-notes-determination-l.c gabc/gabc-score-determination-l.h gabc/gabc-score-determination-y.c gabc/gabc-score-determination-y.h
rm -rf ./.deps dump/.deps gabc/.deps gregoriotex/.deps
rm -f Makefile
Making maintainer-clean in examples
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
rm -f Makefile
Making maintainer-clean in tex
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
rm -f Makefile
Making maintainer-clean in contrib
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
rm -f Makefile
Making maintainer-clean in fonts
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
test -z "gregorio.ttf greciliae.ttf parmesan.ttf greextra.ttf gregall.ttf gresgmodern.ttf" || rm -f gregorio.ttf greciliae.ttf parmesan.ttf greextra.ttf gregall.ttf gresgmodern.ttf
rm -f Makefile
Making maintainer-clean in doc
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
latexmk -quiet -c -f -jobname=GregorioRef-3_0_0 GregorioRef.tex
latexmk -quiet -c -f -jobname=GregorioNabcRef-3_0_0 GregorioNabcRef.tex
rm -rf _minted* factus.gtex veni.gtex
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
test -z "GregorioRef-3_0_0.pdf GregorioNabcRef-3_0_0.pdf" || rm -f GregorioRef-3_0_0.pdf GregorioNabcRef-3_0_0.pdf
rm -f Makefile
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -rf ./autom4te.cache
rm -f Makefile
rps-mac:gregorio RPS$ ./build.sh --arch=x86_64 --force=autoreconf
Creating build files using Autotools

Configuring build files; options:    
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... rm: conftest.dSYM: is a directory
yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -ll
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for windres... no
checking whether C compiler accepts -fstack-protector-strong... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -Wformat... yes
checking whether C compiler accepts -Werror=format-security... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether the linker accepts -Wl,-z,relro... no
checking whether the linker accepts -Wl,-z,now... no
checking whether the linker accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdint.h... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating contrib/Makefile
config.status: creating doc/Makefile
config.status: creating tex/Makefile
config.status: creating fonts/Makefile
config.status: creating src/config_.h
config.status: executing depfiles commands

Building Gregorio; options:
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregorio-characters.o -MD -MP -MF .deps/gregorio-characters.Tpo -c -o gregorio-characters.o `test -f 'characters.c' || echo './'`characters.c
mv -f .deps/gregorio-characters.Tpo .deps/gregorio-characters.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregorio-gregorio-utils.o -MD -MP -MF .deps/gregorio-gregorio-utils.Tpo -c -o gregorio-gregorio-utils.o `test -f 'gregorio-utils.c' || echo './'`gregorio-utils.c
mv -f .deps/gregorio-gregorio-utils.Tpo .deps/gregorio-gregorio-utils.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregorio-messages.o -MD -MP -MF .deps/gregorio-messages.Tpo -c -o gregorio-messages.o `test -f 'messages.c' || echo './'`messages.c
mv -f .deps/gregorio-messages.Tpo .deps/gregorio-messages.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregorio-struct.o -MD -MP -MF .deps/gregorio-struct.Tpo -c -o gregorio-struct.o `test -f 'struct.c' || echo './'`struct.c
struct.c:50:20: warning: unused function 'max' [-Wunused-function]
static inline char max(char a, char b)
                   ^
1 warning generated.
mv -f .deps/gregorio-struct.Tpo .deps/gregorio-struct.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregorio-unicode.o -MD -MP -MF .deps/gregorio-unicode.Tpo -c -o gregorio-unicode.o `test -f 'unicode.c' || echo './'`unicode.c
mv -f .deps/gregorio-unicode.Tpo .deps/gregorio-unicode.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT dump/gregorio-dump.o -MD -MP -MF dump/.deps/gregorio-dump.Tpo -c -o dump/gregorio-dump.o `test -f 'dump/dump.c' || echo './'`dump/dump.c
dump/dump.c:870:21: warning: 11 enumeration values not handled in switch:
      'GRE_NOTE', 'GRE_GLYPH', 'GRE_FLAT'... [-Wswitch]
            switch (element->type) {
                    ^
1 warning generated.
mv -f dump/.deps/gregorio-dump.Tpo dump/.deps/gregorio-dump.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregoriotex/gregorio-gregoriotex-write.o -MD -MP -MF gregoriotex/.deps/gregorio-gregoriotex-write.Tpo -c -o gregoriotex/gregorio-gregoriotex-write.o `test -f 'gregoriotex/gregoriotex-write.c' || echo './'`gregoriotex/gregoriotex-write.c
gregoriotex/gregoriotex-write.c:1974:29: warning: 18 enumeration values not
      handled in switch: 'GRE_NOTE', 'GRE_GLYPH', 'GRE_ELEMENT'... [-Wswitch]
                    switch (glyph->type) {
                            ^
gregoriotex/gregoriotex-write.c:2179:17: warning: 10 enumeration values not
      handled in switch: '_NO_SIGN', '_PUNCTUM_MORA', '_AUCTUM_DUPLEX'...
      [-Wswitch]
        switch (current_note->signs) {
                ^
gregoriotex/gregoriotex-write.c:2593:25: warning: 20 enumeration values not
      handled in switch: 'GRE_NOTE', 'GRE_GLYPH', 'GRE_ELEMENT'... [-Wswitch]
                switch (glyph->type) {
                        ^
gregoriotex/gregoriotex-write.c:2582:17: warning: 19 enumeration values not
      handled in switch: 'GRE_NOTE', 'GRE_GLYPH', 'GRE_FLAT'... [-Wswitch]
        switch (element->type) {
                ^
gregoriotex/gregoriotex-write.c:2736:47: warning: comparison of constant
      'GRE_END_OF_LINE' (12) with boolean expression is always false
      [-Wtautological-constant-out-of-range-compare]
            || !syllable->next_syllable->type == GRE_END_OF_LINE
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
gregoriotex/gregoriotex-write.c:2737:47: warning: comparison of constant
      'GRE_END_OF_PAR' (15) with boolean expression is always false
      [-Wtautological-constant-out-of-range-compare]
            || !syllable->next_syllable->type == GRE_END_OF_PAR) {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
6 warnings generated.
mv -f gregoriotex/.deps/gregorio-gregoriotex-write.Tpo gregoriotex/.deps/gregorio-gregoriotex-write.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gregoriotex/gregorio-gregoriotex-position.o -MD -MP -MF gregoriotex/.deps/gregorio-gregoriotex-position.Tpo -c -o gregoriotex/gregorio-gregoriotex-position.o `test -f 'gregoriotex/gregoriotex-position.c' || echo './'`gregoriotex/gregoriotex-position.c
gregoriotex/gregoriotex-position.c:738:17: warning: 5 enumeration values not
      handled in switch: 'SP_DEFAULT', 'SP_NO_SPACE', 'SP_ZERO_WIDTH'...
      [-Wswitch]
        switch (element->u.misc.unpitched.info.space) {
                ^
1 warning generated.
mv -f gregoriotex/.deps/gregorio-gregoriotex-position.Tpo gregoriotex/.deps/gregorio-gregoriotex-position.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gabc/gregorio-gabc-elements-determination.o -MD -MP -MF gabc/.deps/gregorio-gabc-elements-determination.Tpo -c -o gabc/gregorio-gabc-elements-determination.o `test -f 'gabc/gabc-elements-determination.c' || echo './'`gabc/gabc-elements-determination.c
mv -f gabc/.deps/gregorio-gabc-elements-determination.Tpo gabc/.deps/gregorio-gabc-elements-determination.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gabc/gregorio-gabc-write.o -MD -MP -MF gabc/.deps/gregorio-gabc-write.Tpo -c -o gabc/gregorio-gabc-write.o `test -f 'gabc/gabc-write.c' || echo './'`gabc/gabc-write.c
mv -f gabc/.deps/gregorio-gabc-write.Tpo gabc/.deps/gregorio-gabc-write.Po
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gabc/gregorio-gabc-glyphs-determination.o -MD -MP -MF gabc/.deps/gregorio-gabc-glyphs-determination.Tpo -c -o gabc/gregorio-gabc-glyphs-determination.o `test -f 'gabc/gabc-glyphs-determination.c' || echo './'`gabc/gabc-glyphs-determination.c
gabc/gabc-glyphs-determination.c:754:17: warning: 28 enumeration values not
      handled in switch: 'S_UNDETERMINED', 'S_PUNCTUM',
      'S_PUNCTUM_END_OF_GLYPH'... [-Wswitch]
        switch (current_note->u.note.shape) {
                ^
1 warning generated.
mv -f gabc/.deps/gregorio-gabc-glyphs-determination.Tpo gabc/.deps/gregorio-gabc-glyphs-determination.Po
flex -o gabc/gabc-score-determination-l.c --header-file=gabc/gabc-score-determination-l.h gabc/gabc-score-determination.l
gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"kpse-dc0d80a-1982"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -arch x86_64 -g -O2  -Wdeclaration-after-statement -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gabc/gregorio-gabc-score-determination-l.o -MD -MP -MF gabc/.deps/gregorio-gabc-score-determination-l.Tpo -c -o gabc/gregorio-gabc-score-determination-l.o `test -f 'gabc/gabc-score-determination-l.c' || echo './'`gabc/gabc-score-determination-l.c
gabc/gabc-score-determination.l:30:10: fatal error: 
      'gabc-score-determination-y.h' file not found
#include "gabc-score-determination-y.h"
         ^
1 error generated.
make[2]: *** [gabc/gregorio-gabc-score-determination-l.o] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
Failed to build Gregorio.
rps-mac:gregorio RPS$ make src/gabc/gabc-score-determination-y.h
make: *** No rule to make target `src/gabc/gabc-score-determination-y.h'.  Stop.
```

**Comment by henryso** [comment]
What do you think of #431?  Shall I merge it here?

**Comment by rpspringuel** [comment]
Built successfully.

Tried the `--with-kpathsea` option and got `configure: error: unable to find the kpathsea library`, which is about what I would expect (since I've not put the library on manually and don't think it comes bundled automatically with anything I've installed).

Now to figure out how to put that library onto my computer and try again.

**Comment by eroux** [comment]
@rpspringuel I'm affraid this won't be easy... What I'm thinking about is a script to build the whole texk/ directory of texlive svn, with gregorio in it, so that we get a statically linked executable... But that will be possible only when it will first arrive in TeXLive svn. This is how LuaTeX solves the kpathsea problem. I admit it's not elegant, but I'm affraid this is the only option to be able to build for Windows with kpathsea for instance.

Anyway, I don't know why, but your gcc outputs more warnings than mine! @henryso some of these warnings are quite interesting, especially the ones by `-Wtautological-constant-out-of-range-compare`, maybe they need fixing?

**Comment by henryso** [comment]
I think all warnings deserve a look.  Different GCC's have different warnings enabled for `-Wall` and `-Wextra`.  That said, it would be much easier to fix these if I could get my GCC to generate them.  Let's open a different issue for that, though.

**Comment by eroux** [comment]
ok. What about merging this?

**Comment by henryso** [comment]
I believe the build was successful for @rpspringuel (the kpse issue aside).  However, I'd like to get confirmation from @jperon before we merge this.

**Comment by eroux** [comment]
ok

**Comment by eroux** [comment]
@henryso I can reproduce these warnings with

    ./configure CC="clang-3.7" CLINKER="clang-3.7"

**Comment by eroux** [comment]
well, I fixed the warnings, it might have fix some actual bugs with end of lines...

**Comment by henryso** [comment]
Lovely, thanks!  Those (!xxx == yyy) warnings were really particularly bad.

**Comment by jperon** [comment]
I get this reply from launchpad : 

    Rejected:
    gregorio_3.0.0+git20150518+26fc6af-1.dsc: Version older than that in the archive. 3.0.0+git20150518+26fc6af-1 <= 3.0.0+git20150518+c76b27a-1

I'll try again tomorrow…

**Comment by jperon** [comment]
PPA build from e1878cc [successful](https://launchpadlibrarian.net/206859781/buildlog_ubuntu-wily-amd64.gregorio_3.0.0%2Bgit20150519%2Be1878cc-1_BUILDING.txt.gz).

**Pull request merged**
