### PR TITLE
many micro-optimizations

### PR DESCRIPTION
**Pull request by eroux**
* draw porrectus bars with ambitus of one
 * redraw normal porrectus bars (narrower)
 * improve design of porrectus bars with ambitus of 5
 * improve design of porrectus auctus with second ambitus of one

### CODE REVIEW

**Comment by eroux** [comment]
Please do not merge now, I'm going to do a few more things

**Comment by eroux** [comment]
This is ready to be merged, I'll make more changes but this is a complete working first step

**Comment by eroux** [comment]
Thanks, I'll try to finish that tonight

**Comment by eroux** [comment]
Well, there are quite a lot of bugs, mainly because you seem to have removed the horizontal episemus for the two first notes of a porrectus (you even removed their numbers completely if I read correctly)... An extreme example showing the bug is `g_b_c` (it also has a misplaced bar)... I think it will be easier to fix for you than for me, as I'm not 100% sure I understand why you removed the case and how you wanted to replace them... What do you think?

**Comment by eroux** [comment]
Oh, could it be that you were relying on the episemus on the first and last note of a porrectus to be close enough to merge? That might work for some cases, but not all... I'll revert that to previous state

**Comment by henryso** [comment]
It's most likely typos on my part.  I'll take a look.

**Comment by eroux** [comment]
The main problem is your handling of the `H_EPISEMUS_FIRST_TWO` in the C code, you treat it as if it was just an episemus on the first note, which it isn't... On small episemus with ambitus of 1 for instance, it's not noticeable if you have an episemus on the last note, but my previous example triggers problems...

**Comment by henryso** [comment]
Yes, it was a typo...  Easy fix... Let me check all the cases.

**Comment by eroux** [comment]
Ok, thanx!

**Comment by henryso** [comment]
The line at the bottom is intentional, I think.  I didn't touch that code.

**Comment by henryso** [comment]
Just so you know, the fact of it being a two-note episemus at the stroke is conveyed by a non-zero ambitus passed in argument 3.  Argument 3 is then passed to the `\gre@char@he@XXX` macro which now accepts an ambitus argument, when 0, they should use \greCpHEpisemusPunctum (unless I made another typo).

**Comment by eroux** [comment]
Thanks! It fixed the line too (which is handled almost like an horizontal episemus, so it's the same code), I'll continue my tests and I'll make a file for the test repository

**Comment by henryso** [comment]
Here's the number chart (or at least the intended number chart)

Porrectus non-auctus amb2=1 | Porrectus non-auctus amb2>1 | Porr. auctus | Porrectus Flexus
--- | --- | --- | ---
9 | 8 | 10 | 10

|| Torculus Resupinus non-auctus amb2=1 | Torculus Resupinus non-auctus amb2>1 | Torculus Resupinus auctus | Torculus Resupinus Flexus
--- | --- | --- | --- | --- | --- | ---
amb1=1 | Punctum | 36 | 22 | 43 | 43
amb1=1 | I. Debilis |  33 | 23 | 40 | 40
amb1=1 | I. Quilisma | 37 | 30 | 44 | 44
amb1=1 | I. Oriscus | 38 | 31 |  45 | 45
amb1>1 | Punctum | 32 | 21 | 39 | 39
amb1>1 | I. Debilis | 33 | 23 | 40 | 40
amb1>1 | I. Quilisma | 34 | 28 | 41 | 41
amb1>1 | I. Oriscus | 35 | 29 | 42 | 42

**Comment by eroux** [comment]
Thanx! That could be converted to ascii table and put in the comments?

**Comment by henryso** [comment]
I apologize for the "lightness" my coding.  I was rushing a bit to unblock you.

**Comment by eroux** [comment]
don't worry, that happens to me quite often!

**Comment by henryso** [comment]
I think #70 can be fixed as part of this by choosing good (smaller?) values for drawing the non-flexus versions of the porrectus stroke episema, making sure they are long enough to melt into an episemus on the final note but not long enough to appear to be covering the final note.  What do you think?

**Comment by eroux** [comment]
This is an interesting idea... So the idea would be that `g_e_g` would do the small version and `g_e_g_` would do the large one? Why not... This would require a few more numbers (that would be required whatever the solution we choose). Well, I've had much less time than I expected tonight, so feel free to take the mutex token back...

**Comment by henryso** [comment]
There should, in any case, be some difference between `g_e_g` and `g_e_g_`, which I think is the crux of #70.  The same would be true pretty much everywhere that you don't use the "flexus" version of the porrectus stroke episemus (meaning whenever you use the non-auctus ambitus-one episemus or the non auctus ambitus-at-least-two episemus).  What are the cases you foresee that need a longer version besides for auctus or flexus?

**Comment by eroux** [comment]
Ok yes, seems consistant... We have to revert 675fba5be4c358c151d6c6629a1fe81767aebefd for this. No you're right, no need to change anything! It will just look a little odd with deminutus (`g_f_g~`), but that certainly doesn't really exist...

**Comment by henryso** [comment]
@eroux Do you foresee many changes remaining for you in the horizontal episemus code for what you're working on here?

**Comment by eroux** [comment]
No, I'll just change the numbers corresponding to new cases in `gregoriotex_find_sign_number`, that's it, you can change everything else

**Comment by eroux** [comment]
@henryso I'm quite happy with the current state, I added a test in gregorio-test, and now gregoria4o looks good, so I think it's ready to merge... please review

**Comment by henryso** [comment]
I will review in detail tonight.

**Comment by henryso** [comment]
I'll admit that reviewing that was an eye-crossing experience, but I assuming the measurements are right, I didn't see anything glaringly out of place.  Merging.

**Comment by eroux** [comment]
Well, if you've tested with greciliae, I don't believe this branch introduces much difference (if at all), but with gregoria4o (which I consider finished now), it's noticeable

**Comment by henryso** [comment]
@eroux Are you referring to #391?  Did you check that I used the correct glyphs in Gregoria?  If you're referring to #375, then yes, I tested with greciliae, but I had to add the changes in #391 for some things to work.

**Comment by eroux** [comment]
I was just referring to your comment "I'll admit that reviewing that was an eye-crossing experience"

**Comment by henryso** [comment]
I see.  Yes, it's fine more-or-less with greciliae.

**Pull request merged**
