### PR TITLE
Allow no-bar syllables to use different offset limits than normal bar…

### PR DESCRIPTION
**Pull request by rpspringuel**
… syllables.

### CODE REVIEW

**Comment by eroux** [comment]
Looks good, ok for me to merge

**Comment by rpspringuel** [comment]
I would hold this merge until after #921 is finished as there are going to be conflicts to be worked out.  Further #921 is already giving me enough trouble without introducing this into the mix on top of it.

**Comment by eroux** [comment]
Sure, that's what I was thinking too

**Comment by eroux** [comment]
If you solve the conflicts you can merge if you want

**Pull request merged**
