### PR TITLE
Changed GregorioRef date to %d-%b-%Y so date components are obvious.

### PR DESCRIPTION
**Pull request by henryso**
Using %d/%m/%y can leave the date components ambiguous depending on where you live, so I propose changing it to %d-%b-%Y (with `LC_TIME` set to `'C'`).  Feel free to close this request without merging if you disagree.

### CODE REVIEW

**Comment by eroux** [comment]
Why not something more human friendly like *April 26th, 2013* ?

**Comment by eroux** [comment]
(sorry, it seems I merged the wrong PR...)

**Comment by henryso** [comment]
It can do something like *April 26, 2013* pretty easily, but to put the proper ordinal *th* would require some extra work.  I don't see the logic in American date ordering, so might I suggest "26 April 2013" instead?

**Comment by eroux** [comment]
I don't see the logic in American date ordering neither... Maybe it would be worth inquiring date formatting in LaTeX?

    \usepackage{datetime}
    \newdate{date}{26}{04}{2015}

then

    \displaydate{date}

(untested). But if it complicates things, I'm fine with *26 April 2015*.

**Comment by henryso** [comment]
New pull request is #330.

**Pull request merged**
