### PR TITLE
Rough implementation of per-line spacing adjustment.

### PR DESCRIPTION
**Pull request by henryso**

### CODE REVIEW

**Comment by eroux** [comment]
That seems good to me! A few things missing:

- conditional to make it happen or not
- maybe better glyph IDs, the reason is that if a user inserts a score or adds a glyph in a score, with the current implementation, it might cause height changes in the middle of a line of another score, and this will look really wrong... I think the idea is to make things as good as possible at each run, though 2 runs would be necessary to get the final result
- maybe a message telling the user that Gregorio had to change some height (if it did), and that the score might look weird, but it should be ok after a second compilation

A few tests to make:

- include the same score twice at two different places (won't matter with current glyph ID implementation, but might with another
- performance: did you notice a change?

**Comment by henryso** [comment]
Addressing your points in order.

- I will work on conditional once I'm satisfied with the general implementation.  I had assumed that this would not be switchable, so this means fewer things will need to be removed as dead code.  I'm glad you cleared that up before I got too far.
- Regarding glyph IDs, attribute values are 32-bit integers, so I suppose we'll need an indirection table.  I'll have to think about this one a bit more.
- There is already a message generated by `gregoriotex.lua` in `write_greaux`, unless you mean you want to change the wording of this message (currently the message is `Line heights may have changed. Rerun to fix heights.`)
- I will test including the score in multiple places
- I didn't notice a performance change on a single pass, but I was only using small test scores and not testing it explicitly.  The big performance killer is the necessary second pass.

Thanks for reviewing.  I'll work on your suggestions and be back with a new cut in a few days.

**Comment by eroux** [comment]
the message is ok, you can leave it like this. In real life, most people won't have to compile twice all the time, only when they see some ugly things, so the most important is not to make one compilation considerably slower... Maybe there could be a mode where the data is only read, not written? This way if someone just works on some text and not on the scores (in a big document such as a book), he can turn off most of this processing?

**Comment by henryso** [comment]
How should this read-only mode be activated? TeX command? Environment variable?

**Comment by eroux** [comment]
I don't think most users will know how to handle environment variables, so I had a TeX command in mind... I'm affraid this won't be used a lot, but for very big projects it will certainly matter.

**Comment by henryso** [comment]
My only "concern," if you can even call it that, is that a TeX switch means you need to change your sources to make it work, but if that's standard practice in the TeX world for this kind of thing, then there's no problem.

**Comment by eroux** [comment]
This is of course something only for "experts" working on very large documents, so they should know what they are doing... See for instance the "draft" mode of LaTeX...

**Comment by henryso** [comment]
Please see the changes in 710f5db1d45f6f5ee2228bca183aa42915af6fb6 and let me know if this is a good solution to the glyph id problem.

**Comment by eroux** [comment]
it will do yes... I tend to like my initial idea of having a random ID per score, allowing insertion of a score between two other scores without destroying all the spacings afterwards, but this is already significantly better than the previous solution! Maybe a `\greRandomId{xxx}` in the `.gtex` file would be enough, with just a small mechanism to add `.1`, `.2`, etc. to the ID if the score is included several times... What do you think?

**Comment by henryso** [comment]
If I seed the random number generator by `time(NULL)`, there's a very good chance for collision if all the gabc files are compiled at once, up front.  Additionally, this causes a problem (as noted in #441) with force-compiled scores.

I pulled in the GPL SHA-1 digest code from mbed TLS and hooked it into the score determination lexer.  This way, I generate an SHA-1 digest while parsing the gabc file and use it as the unique score ID.

Please see #517 for these changes.  Does this suffice for score ID?

**Comment by eroux** [comment]
I think so, thanks a lot!

**Pull request merged**
