### PR TITLE
Unify Version Numbers.

### PR DESCRIPTION
**Pull request by eschwab**
Addresses #87.

Removes the gregoriotex_api version and replaces it with one
gregorio_version.

### CODE REVIEW

**Comment by rpspringuel** [comment]
This is my fault (since I wrote it wrong in the first place), but looking at http://semver.org/, it should be 3.0.0-beta, not 3.0.beta.

Also, please note the changes in CHANGELOG.

**Comment by eschwab** [comment]
I'm done for the night, Will update the CHANGELOG tomorrow.

**Comment by eschwab** [comment]
This should be good to go now.

**Comment by eschwab** [comment]
No more false starts this time. If this looks good, merge away!

**Comment by rpspringuel** [comment]
Hmm... I've been top posting my additions to CHANGELOG and I noticed that you bottom posted yours.  Does it matter which we do?  Should it?

The code changes look good on inspection, but I don't have time to run any tests tonight to double check.  I'll make some time for that tomorrow and merge if I don't find anything wrong.  (Unless someone beats me to it.)

**Comment by eschwab** [comment]
I'm not sure it should matter where items are noted in the CHANGELOG. My thought is that as long as it is noted under the right release number its fine. But then it may be easier to dig through the commit history if the CHANGLOG is kept chronological.

**Comment by eroux** [comment]
I'm not sure it's the best place to discuss this, but I was asking myself one question: if we now use SemVer, this means that users don't have to compile their score when changing from x.y.z to x.y+.z nor to x.y.z+1, but only when changing to x+1.y.z. Is it taken into consideration into version checking?

**Comment by eschwab** [comment]
No, at this point any change in version number requires the score to be recompiled. I'm thinking that this PR only deals with unifying the version numbers and make a separate issue to change the rules for version checking. I can take care of that also, but these two tasks are different enough that it may be better to have separate commit chains for each.

**Comment by eroux** [comment]
Sure, it was just a reminder, it's no emergency, it can be dealt with separately

**Comment by rpspringuel** [comment]
Time got away from me today and my schedule tomorrow is too tight to work on this.  As a result it'll be Friday before I can double check this.  If someone else can get to this before then, feel free.

**Comment by rpspringuel** [comment]
When I changed the version number and ran `VersionUpdate.py` to test, I found the following bugs:

1. the `-beta` didn't get removed from the version number in the iss file.
2. `gregoriotex.h` was not modified
3. `gregoriotex.lua` was not modified

**Comment by rpspringuel** [comment]
Everything seems to be working great now.

**Pull request merged**
