### PR TITLE
Tmp gre

### PR DESCRIPTION
**Pull request by rpspringuel**
Trying to solve some errors when it come to compilations of files in unusual locations.

Addresses several issues: #1542 #1541 #1393 

@jperon and @Nokel81 I would appreciate it if you could give this a try and see if your particular issue gets solved in an acceptable manner by this change.

I'll add documentation after receiving feedback on the fix.

### CODE REVIEW

**Comment by rpspringuel** [comment]
This fixes the issues I've been having with directory writing problems.  I haven't been able to test all the variations though, so I would appreciate it if @jperon, @Nokel81, and @MaestroGlanz would please check their particular circumstances to see if this works for them.

**Comment by Nokel81** [comment]
I'll see if I have some time to set up a windows development environment

**Comment by rpspringuel** [comment]
I've been using this branch on a project of mine since creating this pull request without problems so I'm going to merge on Monday if no one objects.

**Comment by henryso** [comment]
I don't fully understand what the lua code is doing (on the TeX side), but since this is battle-tested, I'm ok with the merge.

**Review by henryso — APPROVED** [review]
I don't fully understand what the lua code is doing (on the TeX side), but since this is battle-tested, I'm ok with the merge.

**Comment by eschwab** [comment]
Looks fine to me. So much boilerplate dealing with `/` vs `\`

**Comment by johnnysteen** [comment]
I really need this update - when will it be available through TeX Live? Or is there a windows build available?

**Comment by rpspringuel** [comment]
To be honest, I'd forgotten we hadn't initiated a release for this.  I'll see to it that we get one going for inclusion in TeX Live 2025.

**Comment by johnnysteen** [comment]
Thanks brother!

**Pull request merged**
