### PR TITLE
Issue 454

### PR DESCRIPTION
**Pull request by jakubjelinek**
So, at least all the upper braces seem to work fine:
initial-style: 0;
%%
(c4)
in(j)<b>dú</b>(jr[ocba:1;4mm])tus(ih) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:0{])tus(ih[ocba:0}]) est:(j.)
in(j)<b>dú</b>(jr[ocba:0{])tus(ih[ocba:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:1{])tus(ih[ocba:0}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:1{])tus(ih[ocba:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:0{])---tus(ih[ocba:0}]) est:(j.)
in(j)<b>dú</b>(jr[ocba:0{])---tus(ih[ocba:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:1{])---tus(ih[ocba:0}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocba:1{])---tus(ih[ocba:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocb:0{])--tus(ih[ocb:0}]) est:(j.)
in(j)<b>dú</b>(jr[ocb:0{])--tus(ih[ocb:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocb:1{])--tus(ih[ocb:0}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ocb:1{])--tus(ih[ocb:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ob:0{])----tus(ih[ob:0}]) est:(j.)
in(j)<b>dú</b>(jr[ob:0{])----tus(ih[ob:1}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ob:1{])----tus(ih[ob:0}]) est:(j.) (::Z)
in(j)<b>dú</b>(jr[ob:1{])----tus(ih[ob:1}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ub:0{])------tus(ih[ub:0}]) est:(j.)
%in(j)<b>dú</b>(jr[ub:0{])------tus(ih[ub:1}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ub:1{])------tus(ih[ub:0}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ub:1{])------tus(ih[ub:1}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ocba:0{][ub:0{])------tus(ih[ub:0}][ocba:0}]) est:(j.)
%in(j)<b>dú</b>(jr[ocba:0{][ub:0{])------tus(ih[ub:1}][ocba:1}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ocba:1{][ub:1{])------tus(ih[ub:0}][ocba:0}]) est:(j.) (::Z)
%in(j)<b>dú</b>(jr[ocba:1{][ub:1{])------tus(ih[ub:1}][ocba:1}]) est:(j.) (::)

The underbraces and combinations of both seem to misbehave, haven't yet figured out what's wrong with that.

### CODE REVIEW

**Comment by jakubjelinek** [comment]
Even the:
in(j)dú(jr[ub:0{])------tus(ih[ub:0}]) est:(j.)
in(j)dú(jr[ub:0{])------tus(ih[ub:1}]) est:(j.) (::Z)
in(j)dú(jr[ub:1{])------tus(ih[ub:0}]) est:(j.) (::Z)
in(j)dú(jr[ub:1{])------tus(ih[ub:1}]) est:(j.) (::Z)
in(j)dú(jr[ocba:0{][ub:0{])------tus(ih[ub:0}][ocba:0}]) est:(j.)
in(j)dú(jr[ocba:0{][ub:0{])------tus(ih[ub:1}][ocba:1}]) est:(j.) (::Z)
in(j)dú(jr[ocba:1{][ub:1{])------tus(ih[ub:0}][ocba:0}]) est:(j.) (::Z)
in(j)dú(jr[ocba:1{][ub:1{])------tus(ih[ub:1}][ocba:1}]) est:(j.) (::)
should be now hopefully fixed, let me retest.

**Comment by jakubjelinek** [comment]
Ok, verified (made new rpms from the branch and tested with them installed).

**Comment by henryso** [comment]
Out of curiosity, how do you handle braces that cross lines?

**Comment by jakubjelinek** [comment]
Braces that cross lines is not really handled right now and I don't really have a use-case for them now,
guess supporting it would be some more work.  And even more if it would support more spanning of more than one line.  For the easier case, supposedly one could determine it by end x position < start x position, but then we need to record somewhere also some horizontal position at the end of line
and perhaps some horizontal position at the start of the next line.  With that info, what exactly would we emit?  Two copies of the brace, one spanning from the start till some spot near end of line, and another same one spanning from the end to the left up to the start of line?  Or just the first one?
Or another option is to disable line breaking in between them.

**Comment by henryso** [comment]
Regarding braces that cross lines:

If you don't want to implement it now (which is valid given there are no use cases), then I would omit the brace, with a warning that a brace has been omitted for crossing the line.  This limitation should, of course be documented.

If you want to implement it now, both options (two copies of the brace / disabling line breaking) make sense.  I suppose most people would want to disable line breaking, but it is possible that someone would want a really long braced phrase that is expected to break into two lines.  As there is no use case, we can't know which is better to implement, or if both should be, with user-selected behavior, or if there is some other, more useful option.

I think it's safe to punt on this issue, and omit a brace on a broken line, with warning.  Then when a use case comes up, we can build around it.

**Comment by henryso** [comment]
Side note: Do we want to consider drawing the braces using something like tikz instead of stretching a glyph?  I admit that looking at your test cases with all the different braces looks funny, from a font-weight perspective, especially the stretched-out round (over- and under-) braces.

**Comment by eroux** [comment]
That's a good point. I used to draw chironomic signs in metapost, which is useable directly into LuaTeX (and doesn't require big packages like tikz), this seems a good way to explore, but tikz may be fine too (I've never used it)..

**Comment by jakubjelinek** [comment]
Ok, I've added a hack to emit a warning if the end position is smaller than start position, if the braces would span multiple lines but the end position is greater than the start position, it will just emit the brace above the first score line between the two positions.  And I've bumped the fallback length to 2mm, 1mm is too narrow to recognize even what kind of brace it is.

**Comment by henryso** [comment]
Have you checked the dump and gabc format output?  (I won't be able to check this myself until this evening.)

**Comment by jakubjelinek** [comment]
Not sure what exactly you mean by that.  I've certainly verified the *.gtex generated by gregorio, and think e.g. the XML output is removed.

**Comment by henryso** [comment]
I mean if you run `gregorio -F dump` and `gregorio -F gabc`, that you get sensible output.

**Comment by jakubjelinek** [comment]
From what I can see, all the braces are just turned into the gregorioTeX macros during parsing, and -F dump shows them as the TeX macros (before and afterwards) and -F gabc puts them into [nv:...] also as TeX macros.

**Comment by henryso** [comment]
Then I'd say this is good to merge. We can handle multi-line braces when needed.

**Pull request merged**
