### PR TITLE
Added "firstletter" lyric centering.

### PR DESCRIPTION
**Pull request by henryso**
As discussed on the gregorio-devel mailing list.  Gregorio will produce five-argument calls to the syllable-setting macros in order to provide the extra break-down of the lyric after the first character.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by henryso** [comment]
The gabc->gtex tests fail as expected.  Everything else passes.  I will also add an additional test specifically for the new feature if/when this is merged.

**Comment by rpspringuel** [comment]
This TeX code looks a lot nicer than the the pipe version.  Just one thing I'd change.  Can you add a short verbal description of the cases when using `\ifcase` in addition to identifying the number?  It'll make things easier to read if someone has to revisit this code well down the line.

**Comment by henryso** [comment]
Done.

**Comment by eroux** [comment]
ok for me!

**Pull request merged**
