### PR TITLE
Feature/fix 1285

### PR DESCRIPTION
**Pull request by rpspringuel**
Addresses #1285 

I've also included the various code clean-ups that I discovered while working on this.

### CODE REVIEW

**Comment by henryso** [comment]
I think this needs
- a CHANGELOG.md entry
- entries for `\gre@save@additionalspaces` and `\gre@restore@additionalspaces` in Command_Index_internal.tex

**Comment by rpspringuel** [comment]
Done.

**Comment by henryso** [comment]
Assuming everything is tested and working after those renames, I think this looks fine.

**Comment by rpspringuel** [comment]
I just double checked the tests and we're clear.

**Pull request merged**
