### PR TITLE
Added support for square brackets around notes.

### PR DESCRIPTION
**Pull request by henryso**
Part of the implementation for #844.

No tests change, but I added a new one to exercise the new feature.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Wonderful, thanks a lot! The only thing I would change is to put the extremities of the brackets further from the staff lines (closer to the middle of the lines)... What do you think? (it must be changed in the font right?)

**Comment by henryso** [comment]
I don't think it's as simple as a font change, but I'll try.

**Comment by eroux** [comment]
Ok

**Comment by henryso** [comment]
It looks like we'll need three:

- a short bracket for typical cases where the extrema are both on a space
- a long bracket for typical cases where the extrema are both on a line
- the current size bracket for cases where one extremum is on a space and one is on a line (but shifted up or down accordingly); this case would also handle weird cases below and above the staff.

This is turning out to be a bit complex, so it may take me some time.

**Comment by henryso** [comment]
I made the changes described above.  Please review.

**Comment by eroux** [comment]
I think this is really perfect, thank you very much!

**Pull request merged**
