### PR TITLE
fix #259

### LINKED ISSUE #259: error in configure when flex or bison is not present
Currently, the configure script doesn't output an error when flex or bison are not found, the error occurs in make, but having the error in the configure script would be more in the autotools philosophy.

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by henryso** [comment]
`make distcheck` fails:

```
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../plugins/gabc -I../../include -I../../../include -I../../../lib -D_FORTIFY_SOURCE=2 -L../../lib -g -O2 -Wformat -Werror=format-security -MT gabc-score-determination-l.lo -MD -MP -MF .deps/gabc-score-determination-l.Tpo -c ../../../plugins/gabc/gabc-score-determination-l.c  -fPIC -DPIC -o .libs/gabc-score-determination-l.o
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined [enabled by default]
<built-in>:0:0: note: this is the location of the previous definition
gabc-score-determination.l:29:40: fatal error: gabc-score-determination-y.h: No such file or directory
compilation terminated.
Makefile:462: recipe for target 'gabc-score-determination-l.lo' failed
make[3]: *** [gabc-score-determination-l.lo] Error 1
make[3]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build/plugins/gabc'
Makefile:356: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build/plugins'
Makefile:392: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build'
Makefile:592: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```

**Comment by eroux** [comment]
is it better now?

**Comment by henryso** [comment]
It fails in a different place now.
```
make[3]: Entering directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build/doc'
latexmk -pdf -pdflatex='lualatex --shell-escape %O %S' -jobname=GregorioRef-3_0_0-rc2 GregorioRef.tex
Latexmk: This is Latexmk, John Collins, 11 Nov. 2012, version: 4.35.
**** Report bugs etc to John Collins <collins at phys.psu.edu>. ****

------------
Latexmk: Could not find file [GregorioRef.tex].
-- Use the -f option to force complete processing.
Makefile:439: recipe for target 'GregorioRef-3_0_0-rc2.pdf' failed
make[3]: *** [GregorioRef-3_0_0-rc2.pdf] Error 11
make[3]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build/doc'
Makefile:492: recipe for target 'distdir' failed
make[2]: *** [distdir] Error 1
make[2]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build'
Makefile:585: recipe for target 'dist' failed
make[1]: *** [dist] Error 2
make[1]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build'
Makefile:592: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```
Note: `/home/inxi/develop/gregorio/gregorio-3.0.0-rc2/_build/doc` only has a `Makefile` in it.

**Comment by eroux** [comment]
Building from a clean new repo clone, I can't see your bug, but there was still something with the lex/bison files, which I fixed... Does your bug also pops up if you try with a clean clone?

**Comment by henryso** [comment]
git+ssh://git@github.com/gregorio-project/gregorio.git

**Comment by henryso** [comment]
Resetting the `doc` directory to pristine state indeed allows `make distcheck` to complete successfully. Thanks.

**Comment by henryso** [comment]
In terms of using the tarball as-is with `./build.sh`, it seems to work fine.  However, if you run make clean, it will delete some of the bison- and flex-generated files, so you won't be able to make again.  I don't know if we can or should fix this.  It will also happily delete the .ttf files in `fonts`, but this latter problem is fixed in `develop`.

**Comment by eroux** [comment]
hmmm that's right, `clean` in `plugins/gabc/` and `fonts/` should be replaced by `distclean` right?

**Comment by eroux** [comment]
done

**Comment by henryso** [comment]
Looks good. Merging.

**Pull request merged**
