### PR TITLE
changing C code style to KR

### PR DESCRIPTION
**Pull request by eroux**
(not actually indenting files)

### CODE REVIEW

**Comment by rpspringuel** [comment]
Do you have any links to samples of the various indentation styles (preferably of the same code) so that those of us who are less familiar with them can have a visual reference to comment on?

**Comment by henryso** [comment]
###### indent -gnu
```
void
gregoriotex_write_element (FILE * f,
                           gregorio_syllable * syllable,
                           gregorio_element * element)
{
  gregorio_glyph *current_glyph = element->first_glyph;
  while (current_glyph)
    {
      if (current_glyph->type == GRE_SPACE)
        {
          // we assume here that it is a SP_ZERO_WIDTH, the only one a glyph
          // can be
          fprintf (f, "\\greendofglyph{1}%%\n");
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_TEXVERB_GLYPH && current_glyph->texverb)
        {
          fprintf (f,
                   "%% verbatim text at glyph level:\n%s%%\n%% end of verbatim text\n",
                   current_glyph->texverb);
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_FLAT)
        {
          fprintf (f, "\\greflat{%c}{0}%%\n", current_glyph->glyph_type);
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_NATURAL)
        {
          fprintf (f, "\\grenatural{%c}{0}%%\n", current_glyph->glyph_type);
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_SHARP)
        {
          fprintf (f, "\\gresharp{%c}{0}%%\n", current_glyph->glyph_type);
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_BAR)
        {
          gregoriotex_write_bar (f, current_glyph->glyph_type,
                                 current_glyph->liquescentia, INSIDE_BAR);
          current_glyph = current_glyph->next;
          continue;
        }
      if (current_glyph->type == GRE_TEXVERB_GLYPH && current_glyph->texverb)
        {
          fprintf (f, "%s", current_glyph->texverb);
          current_glyph = current_glyph->next;
          continue;
        }
      // at this point glyph->type is GRE_GLYPH
      gregoriotex_write_glyph (f, syllable, element, current_glyph);
      if (current_glyph->next && current_glyph->next->type == GRE_GLYPH)
        {
          if (is_puncta_inclinata (current_glyph->next->glyph_type)
              || current_glyph->next->glyph_type == G_PUNCTA_INCLINATA)
            {
              fprintf (f, "\\greendofglyph{9}%%\n");
            }
          else
            {
              fprintf (f, "\\greendofglyph{0}%%\n");
            }
        }
      current_glyph = current_glyph->next;
    }
}
```

###### indent -kr
```
void
gregoriotex_write_element(FILE * f,
                          gregorio_syllable * syllable,
                          gregorio_element * element)
{
    gregorio_glyph *current_glyph = element->first_glyph;
    while (current_glyph) {
        if (current_glyph->type == GRE_SPACE) {
            // we assume here that it is a SP_ZERO_WIDTH, the only one a glyph
            // can be
            fprintf(f, "\\greendofglyph{1}%%\n");
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_TEXVERB_GLYPH
            && current_glyph->texverb) {
            fprintf(f,
                    "%% verbatim text at glyph level:\n%s%%\n%% end of verbatim text\n",
                    current_glyph->texverb);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_FLAT) {
            fprintf(f, "\\greflat{%c}{0}%%\n", current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_NATURAL) {
            fprintf(f, "\\grenatural{%c}{0}%%\n",
                    current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_SHARP) {
            fprintf(f, "\\gresharp{%c}{0}%%\n", current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_BAR) {
            gregoriotex_write_bar(f, current_glyph->glyph_type,
                                  current_glyph->liquescentia, INSIDE_BAR);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_TEXVERB_GLYPH
            && current_glyph->texverb) {
            fprintf(f, "%s", current_glyph->texverb);
            current_glyph = current_glyph->next;
            continue;
        }
        // at this point glyph->type is GRE_GLYPH
        gregoriotex_write_glyph(f, syllable, element, current_glyph);
        if (current_glyph->next && current_glyph->next->type == GRE_GLYPH) {
            if (is_puncta_inclinata(current_glyph->next->glyph_type)
                || current_glyph->next->glyph_type == G_PUNCTA_INCLINATA) {
                fprintf(f, "\\greendofglyph{9}%%\n");
            } else {
                fprintf(f, "\\greendofglyph{0}%%\n");
            }
        }
        current_glyph = current_glyph->next;
    }
}
```

###### indent -linux
```
void
gregoriotex_write_element(FILE * f,
                          gregorio_syllable * syllable,
                          gregorio_element * element)
{
        gregorio_glyph *current_glyph = element->first_glyph;
        while (current_glyph) {
                if (current_glyph->type == GRE_SPACE) {
                        // we assume here that it is a SP_ZERO_WIDTH, the only one a glyph
                        // can be
                        fprintf(f, "\\greendofglyph{1}%%\n");
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_TEXVERB_GLYPH
                    && current_glyph->texverb) {
                        fprintf(f,
                                "%% verbatim text at glyph level:\n%s%%\n%% end of verbatim text\n",
                                current_glyph->texverb);
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_FLAT) {
                        fprintf(f, "\\greflat{%c}{0}%%\n",
                                current_glyph->glyph_type);
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_NATURAL) {
                        fprintf(f, "\\grenatural{%c}{0}%%\n",
                                current_glyph->glyph_type);
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_SHARP) {
                        fprintf(f, "\\gresharp{%c}{0}%%\n",
                                current_glyph->glyph_type);
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_BAR) {
                        gregoriotex_write_bar(f, current_glyph->glyph_type,
                                              current_glyph->liquescentia,
                                              INSIDE_BAR);
                        current_glyph = current_glyph->next;
                        continue;
                }
                if (current_glyph->type == GRE_TEXVERB_GLYPH
                    && current_glyph->texverb) {
                        fprintf(f, "%s", current_glyph->texverb);
                        current_glyph = current_glyph->next;
                        continue;
                }
                // at this point glyph->type is GRE_GLYPH
                gregoriotex_write_glyph(f, syllable, element, current_glyph);
                if (current_glyph->next
                    && current_glyph->next->type == GRE_GLYPH) {
                        if (is_puncta_inclinata(current_glyph->next->glyph_type)
                            || current_glyph->next->glyph_type ==
                            G_PUNCTA_INCLINATA) {
                                fprintf(f, "\\greendofglyph{9}%%\n");
                        } else {
                                fprintf(f, "\\greendofglyph{0}%%\n");
                        }
                }
                current_glyph = current_glyph->next;
        }
}
```

###### indent -origvoid
```
gregoriotex_write_element(FILE * f,
                          gregorio_syllable * syllable,
                          gregorio_element * element)
{
    gregorio_glyph *current_glyph = element->first_glyph;
    while (current_glyph) {
        if (current_glyph->type == GRE_SPACE) {
            // we assume here that it is a SP_ZERO_WIDTH, the only one a
            // glyph
            // can be
            fprintf(f, "\\greendofglyph{1}%%\n");
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_TEXVERB_GLYPH
            && current_glyph->texverb) {
            fprintf(f,
                    "%% verbatim text at glyph level:\n%s%%\n%% end of verbatim text\n",
                    current_glyph->texverb);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_FLAT) {
            fprintf(f, "\\greflat{%c}{0}%%\n", current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_NATURAL) {
            fprintf(f, "\\grenatural{%c}{0}%%\n",
                    current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_SHARP) {
            fprintf(f, "\\gresharp{%c}{0}%%\n", current_glyph->glyph_type);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_BAR) {
            gregoriotex_write_bar(f, current_glyph->glyph_type,
                                  current_glyph->liquescentia, INSIDE_BAR);
            current_glyph = current_glyph->next;
            continue;
        }
        if (current_glyph->type == GRE_TEXVERB_GLYPH
            && current_glyph->texverb) {
            fprintf(f, "%s", current_glyph->texverb);
            current_glyph = current_glyph->next;
            continue;
        }
        // at this point glyph->type is GRE_GLYPH
        gregoriotex_write_glyph(f, syllable, element, current_glyph);
        if (current_glyph->next && current_glyph->next->type == GRE_GLYPH) {
            if (is_puncta_inclinata(current_glyph->next->glyph_type)
                || current_glyph->next->glyph_type == G_PUNCTA_INCLINATA) {
                fprintf(f, "\\greendofglyph{9}%%\n");
            } else {
                fprintf(f, "\\greendofglyph{0}%%\n");
            }
        }
        current_glyph = current_glyph->next;
    }
}
```

**Comment by eroux** [comment]
@rpspringuel does `-kr` look good to you?

**Comment by rpspringuel** [comment]
Thanks. I'll take a look at the details when I'm not on such a small screen.

**Comment by rpspringuel** [comment]
`-kr` looks fine.  Indeed, other than the amount of indent, I can't spot any immediate differences between the last three.  `-gnu` I think goes a little overboard with giving `{` their own line and indentation.

**Comment by eroux** [comment]
Next step will be to indent all files, but I've already seen indent output invalid C, so it should be done cautiously...

**Pull request merged**
