### PR TITLE
Check to avoid clobbering the input file and GregorioTeX installation cleanup.

### PR DESCRIPTION
**Pull request by henryso**
Fix for https://github.com/gregorio-project/gregorio/issues/95

### CODE REVIEW

**Comment by henryso** [comment]
Implemented https://github.com/gregorio-project/gregorio/issues/97

**Comment by eschwab** [comment]
I'm getting a error:

    $ cd fonts
    # make install
    -------
    make: *** No rule to make target 'install'. Stop.

How should the install process be done with this patch?

**Comment by henryso** [comment]
instead of `cd fonts; make install`, run `install-gtex.sh var:TEXMFLOCAL` from the root gregorio directory.

I am working on an install-everything script, so I haven't documented that any more than what you see in the install-gtex.sh file.

**Comment by henryso** [comment]
Thinking about this, I should probably put in an install "rule" which tells you to run `install-gtex.sh` instead.

**Comment by eschwab** [comment]
Ok, I got the `install-gtex.sh` working. I build a package for my distro (Arch) to keep things organized and easy to switch between builds, thanks for the `dir:` var.

    echo '%%\n(c3) r(f)` > test.tex
    gregorio -o test.tex test.tex

Fails, and wrecks test.tex.

**Comment by henryso** [comment]
I wasn't sure I should guard an explicit file name in the case of doing some weird stuff with pipes.  It's probably unlikely anyone is doing that, but do you think I should extend this check to explicitly specified file names?

**Comment by eroux** [comment]
@henryso : maybe it would be easier if there was a `--local` and `--global` option that would be shortcuts for `var:TEXMFHOME` and `var:TEMFLOCAL`? That would ease the invocation for most users...

@eschwab I don't believe "C" is a relevant label here, it has nothing to do with the C language... maybe "packaging" or "scripts" would be more relevant?

**Comment by henryso** [comment]
I didn't realize that checking something in would add to my existing pull request.  I'll see if I can fix it, if only as an exercise for myself to get it right.  If I can figure it out, I will close this this request.

**Comment by henryso** [comment]
Breaking into two individual pull requests.

**Pull request closed without merging**
