### PR TITLE
gregoriotex.lua: overhaul access to Luatex fonts tables

### PR DESCRIPTION
**Pull request by phi-gamma**
Related to

    https://github.com/gregorio-project/gregorio/issues/717
    https://github.com/lualatex/luaotfload/issues/308

The font table was indexed directly which is unsafe when using
Luaotfload. Instead, font.getfont() should be used which is overridden
by the fontloader. Due to caching, those accesses are faster too than
indexing the font table directly as well as using the builtin
font.getfont() API.

In order to facilitate future extensions to the code, a number of
frequent lookups have been implemented as accessor functions.

       ----------------------------------------------------
        expecting font id       expecting name
       ----------------------------------------------------
        get_font_by_name()      get_score_font_id()
        get_font_resources()    get_score_font_resources()
       ----------------------------------------------------

The *score_font* varieties look up the string in the ``score_font``
table first. Since in the majority of cases font accesses are followed
directly by a lookup of the ``.resources`` subtable, this is covered by
the *resources* variants.

### CODE REVIEW

**Comment by phi-gamma** [comment]
Hey guys, following the discussion on the list and the referenced
tracker items, I decided to look into Gregorio. There are problems
with how fonts are accessed. Please review the code in this PR, I
can extend / adapt it according to your needs. NB this isn’t tested
at all: I couldn’t get Gregorio installed on my distro without pulling
yet another Texlive install as dependency. *Thus it’s very likely that
the code contains blatant errors.*

Please test whether this works with recent Luaotfload.

**Comment by eroux** [comment]
Thanks a lot, it really helps! Will this work with every (recent) versions of luaotfload?

**Comment by eroux** [comment]
For other developpers: I'm ok to merge this even if you can only test with luaotfload 2.5 (I'll test on monday otherwise)

**Comment by henryso** [comment]
Supplanted by #719.

**Pull request closed without merging**
