### PR TITLE
Fix for #159

### PR DESCRIPTION
**Pull request by henryso**
Fix for #159

### CODE REVIEW

**Comment by eroux** [comment]
I don't know if some scripts can detect this, but it's a common error people do...

**Comment by rpspringuel** [comment]
I can easily write a sed script that adds a `%` to every line that doesn't already end in a comment.  This could then be applied as a clean filter to people's setup, thus automatically adding them.  Would that be useful to people?

**Comment by eroux** [comment]
Well, it's more subtle than this... The comments in TeX follow the following non-obvious rules:

 * a comment make TeX ignore
 what follows until the end of line and

**Comment by henryso** [comment]
I think it's better if we write a lint-like tool to look for things like this.  Then let the developer fix as desired.

**Comment by eroux** [comment]
Agreed, but this kind of tools doesn't exist and won't be very easy to write (TeX parsing is just madness)

**Pull request merged**
