### PR TITLE
Fixed compiler warnings.

### PR DESCRIPTION
**Pull request by henryso**

### CODE REVIEW

**Comment by jakubjelinek** [comment]
Just small comment, in post-K&R C, you should use (void) instead of () for functions taking no arguments, both in prototypes and actual function definitions.

**Comment by eroux** [comment]
I didn't know that, thanx! @henryso are you planning to add the `void` now or should I merge?

**Comment by henryso** [comment]
@eroux I will fix the void problem, so please wait a bit.

**Comment by jakubjelinek** [comment]
In C++ () means the same as (void) in C, but in C e.g.
int foo ();
void bar ()
{
  foo (1, 2, 3);
}
is valid, you get no argument type checking in that case.  In K&R the arguments were declared in the definition like:
int foo (x, y, z)
  int x, y, z;
{
  return x + y + z;
}
but the function definition doesn't serve as a prototype.

**Comment by eroux** [comment]
Very interesting, I didn't know the K&R style... apparently it's been deprecated in C11. I've added the `-Wstrict-prototypes` warning.

**Comment by henryso** [comment]
Ok. Ready to merge unless there's some other warning we should enable.

**Comment by eroux** [comment]
Many thanks for this!

**Pull request merged**
