### PR TITLE
Implement oriscus with stem

### PR DESCRIPTION
**Pull request by henryso**
This is my attempt at implementing the oriscus with stem. #76

### CODE REVIEW

**Comment by henryso** [comment]
As a first step, I modified the fonts to add the stemmed oriscus "singleton" figures.  Did I do this correctly?

**Comment by eroux** [comment]
That's perfect, thanx!

**Comment by henryso** [comment]
This is ready for review.

**Comment by eroux** [comment]
This is a go for me, I have not time to test but you can merge it if you tested it. The only doubt I have is about the gabc input: I see no problem in changing `O` meaning, but doing something with `v` or `V` might be more explicit? Like `ioVg` or `iovg`? Not sure about it, what do you think?

**Comment by henryso** [comment]
If you feel strongly about it, then I'll do it, but I don't like the idea of having yet another modifier character.  I see capital-O as "attach this oriscus to the previous note," and if there's no previous note, it adds a stem to "attach it" as in the pressus with this figure in the middle (from #76).  I need to do some more testing.  If it looks good, I will merge it later on.

**Comment by henryso** [comment]
Passes tests satisfactorily.  Merging.

**Comment by eroux** [comment]
Sorry, just remembered something missing from this pull request: adding it to CHANGELOG!

**Pull request merged**
