### PR TITLE
Texrenamingiii

### PR DESCRIPTION
**Pull request by rpspringuel**
This renames the fonts, and thus should complete the texnaming process.

### CODE REVIEW

**Comment by henryso** [comment]
I'm not sure I like "neumebase". There's more stuff in there than just neumes. Though in the end, it doesn't make much difference to the user, I'd be happier with "score" (i.e., `\gre@font@score`). What do you think?

**Comment by rpspringuel** [comment]
I realize there's more than just the neumes, but I don't like "score" because that to me would include stuff like the lyrics, which most certainly aren't typeset with this font.  What about "music"?

**Comment by henryso** [comment]
I would be happy with "music".

**Comment by henryso** [comment]
Looks good.

**Pull request merged**
