### PR TITLE
Corrected the grouping of repercussive glyphs into a single element.

### LINKED ISSUE #928: Line breaks within tristropha
I think after the fix for #868, at least some elements like the tristropha `(hhh)` and bistropha `(hh)` will unexpectedly break across lines, unless the new syntax for inter-glyph space is inserted, i.e. `(h/!h/!h)`.

texshop_image

(using `4.1.0-beta3-develop-8968c0f-3305`)

### PR DESCRIPTION
**Pull request by henryso**
Fixes #928.

Changes some of the existing tests, indicating that what I thought looked correct was, in fact, not correct.  I also added a test that more obviously tests this fix.

I ran coverage and valgrind tests.  No issues to report.

The change log for this fix should be taken out once 4.1 is released.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by rarty** [comment]
Thanks for the quick update. I did some more testing and with this fix all repeated glyphs look correct, but I now notice that some other cases also need to be accounted for (with manual non-breaking spaces or algorithmically), like the pressus `(hhg)`:


texshop_image

**Comment by eroux** [comment]
The patch looks ok, but let's wait for the fix of pressus to be added before merging

**Comment by henryso** [comment]
I need rules to implement a fix.  How do I differ that from some complicated set of neumes that *should* break?  Alternately, I can restore the behavior of indiscriminately gluing everything possible into a single element.  @eroux, do you have any suggestions?

**Comment by eroux** [comment]
I think the rules I had in mind were to "glue" glyphs where the first is a single note (punctum or oriscus), and the second starts by this note, let's start with this, I'll ask my monastic contacts if there are more cases. So the basic idea is to handle all forms of *pressi*, *tristrophae*, *trivirgae*, figures like `(h_h_h_)`, etc.

**Comment by eroux** [comment]
Sorry, maybe it wasn't clear, from a technical point of view, the rule `if previous is single note and next starts with the same pitch, let them in the same element` is the most general one, it includes all others, and it can be repeated multiple times in a row (in the case of *tristropha* for instance).

**Comment by henryso** [comment]
So, going by your repetition rule, `(hhhghih)` should be a single element?

**Comment by eroux** [comment]
Good point... First, I don't see why you would keep `hgh` and `ih` in the same element (it doesn't fit anywhere in the rule above)? But the most important is `hhhgh`... to be honest I do not know... maybe we can keep them in the same element? I also thought about a few more rules:

- when a punctum mora ends a glyph, I think we can break the element afterwards
- I've seen the case of `(ivHGFg)` several times, I think that if a single note is after some punctua inclinata descendens (let's not say anything about a punctum before puncta inclinata ascendens), and this note is one pitch above the final puntum inclinatum, and the note would be in an isolated element (not sure about this last condition, you can just skip it if you want), it should be in the same element as the puncta inclinata (and the virga before)

**Comment by eroux** [comment]
(Well, you certainly need rules without "maybe", so let's keep `hhhgh` in the same element, we may reconsider this for rc2)

**Comment by henryso** [comment]
How about `(ivHGFf)`?

**Comment by eroux** [comment]
I'd say leave it together if the ambitus is < 2, `(ivHGFE)`, `(ivHGFf)` and `(ivHGFg)` are one element... that's quite arbitrary, but that's the best I can come up with right now...

**Comment by henryso** [comment]
This is getting fairly complex.  I have to change the glyph determination in order to make the punctum mora thing work.  This will cause a longer delay due to coverage changing.

**Comment by henryso** [comment]
Perhaps I should ask before doing this.  Currently, `(GH.I)` is a single glyph.  Should I break that into two glyphs: `GH` and `I`?

**Comment by eroux** [comment]
Oh ok... why do you need such changes? This doesn't work by just inspecting if there's a punctum mora on the final note of the previous glyph? You can just ignore unrealistic cases such as `ivHG.F`

**Comment by eroux** [comment]
No, you don't need to (our answers crossed, sorry)

**Comment by henryso** [comment]
That should be it.  I merged develop into it and ran the coverage and valgrind tests.  Let me know if I missed something.

**Comment by eroux** [comment]
Looks perfect, thanks a lot!

**Pull request merged**
