### PR TITLE
Fix 1155

### LINKED ISSUE #1155: problems with end of line hyphen protrusion
The calculation of end of line hyphen protrusion introduced for #845 seem to give strange results in some cases (well, I admit I suspected it was not perfect because of the 50 value I had to give it), for instance in this example (which I don't really manage to "minify"):

gregoriobug

on the second line, the space between the note and the custos is too large compared to the first line, and there is no reason for it. The bug disapears with `\gresethyphenprotrusion{100}`.

Also, this example:

```tex
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage{geometry}
\geometry{a4paper}
\usepackage{gregoriotex}
\usepackage{libertine}
\begin{document}
\grechangecount{endofsyllablepenalty}{-500}%
\grecreatedim{spacebeforeeolcustos}{0 cm plus 0 cm minus 0 cm}{scalable}%

50:

\gabcsnippet{(c3) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) ammmmmmmmmmmmm(g)g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) (g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) Sal(g)va(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g1(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g)}

100:

\gresethyphenprotrusion{100}

\gabcsnippet{(c3) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) ammmmmmmmmmmmm(g)g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) (g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) Sal(g)va(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g1(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g)}

0:

\gresethyphenprotrusion{0}

\gabcsnippet{(c3) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) ammmmmmmmmmmmm(g)g(g) g(g) g(g) g(g) g(g) g(g) g(gg) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) (g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) Sal(g)va(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g1(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g) g(g)}

\end{document}
```

shows that the computation does not work as intended...

### PR DESCRIPTION
**Pull request by eroux**
This fixes #1155 but introduces bugs with syllablerewriting. I think the culprit is https://github.com/gregorio-project/gregorio/commit/e2815a84540bd27af6d982c9e2251f6ec1c0a966 but I really cannot see how... And I have difficulties understanding everything about syllablerewriting... @henryso maybe you could take a look? I think it must be something quite obvious for you, but I'm a bit puzzled...

### CODE REVIEW

**Comment by henryso** [comment]
Did f30589253c0f11dec976fa14b6cbcecf8111b979 fix the syllable rewriting problem?  I was going to suggest something like that.

**Comment by eroux** [comment]
yes it did, thanks!

**Comment by eroux** [comment]
I think it's ready to review

**Comment by henryso** [comment]
I'll try to review this after work today.

**Pull request merged**
