### PR TITLE
Merged develop into fix-9.

### PR DESCRIPTION
**Pull request by henryso**

### CODE REVIEW

**Comment by henryso** [comment]
Compiles and current tests pass. Merging.

**Comment by eschwab** [comment]
Why was this merged directly into master?

**Comment by henryso** [comment]
Thanks for catching that.  I thought I had selected fix-9 as the base branch, but apparently not.

**Comment by henryso** [comment]
Reverting didn't do what I wanted. Still working on it.

**Comment by henryso** [comment]
Ok, I've reverted the change from the history.  I apologize for the mess.

**Pull request merged**
