### PR TITLE
Trace

### PR DESCRIPTION
**Pull request by rpspringuel**
I started this while working on 1285 and found it so useful that I went whole hog and formalized it and applied it to all the internal functions.  It could be applied to Gregorio or user name space functions as well, but I'm less sure that there's a gain from that.

Nominally at least, tests aren't supposed to change as a result of this PR, but #1331 was found as a result of applying this, so that needs to be resolved before this is merged.

### CODE REVIEW

**Comment by henryso** [comment]
Why aren't all macros (i.e., user and gregorio macros) traced as well?

**Comment by rpspringuel** [comment]
I only traced the internal macros because the calling of them tends to be more hidden than the calling of user or Gregorio namespace ones, which actually appear in source files (or gtex ones).  I could add tracing to all macros if that would be more useful.

**Comment by henryso** [comment]
I guess some finesse is needed.  It's probably important to trace user and Gregorio macros that are called from internal macros.

**Comment by rpspringuel** [comment]
That is probably a good point, but I don't know how to design a mechanism to selectively track such macros based on who is calling them.

**Comment by henryso** [comment]
Well, I just meant being selective in which user and gregorio macros are traced.

**Comment by rpspringuel** [comment]
That would be substantially easier to pull off.  Do you have a list of macros which you think should be traced?

**Comment by henryso** [comment]
Based on recent experience, `\GreSetLinesClef`.  Maybe we should just add trace to user and gregorio macros as we encounter the need to do so.  Alternately, I guess we can look for gregorio macros called from other GregorioTeX macros?

**Comment by rpspringuel** [comment]
Okay, I've added tracing to all of the possible functions in gregoriotex-signs.tex.  Take a look at what that does, and let me know if I should do the same for the other files.

**Comment by henryso** [comment]
I think this is good enough.  More can be added as we encounter the need to add it.

**Pull request merged**
