### PR TITLE
Kpse file search

### PR DESCRIPTION
**Pull request by rpspringuel**
When looking for files, GregorioTeX will now employ kpse.find_file if it does not find the file is not in the expected location.  This allows for TEXINPUTS to specify paths to scores and addresses the bug part of #1395.

The one thing I'm not sure about is that I make no attempt to strip off directories before doing the kpse based search.  Should I?

### CODE REVIEW

**Comment by rpspringuel** [comment]
Note, I have not yet run a complete battery of tests.

**Comment by rpspringuel** [comment]
I've done some further testing and have things working a bit better.  However, I'm running into #1393.  I've included a patch here for that issue when kpse is used to find the file, but it would probably be better to figure out a more general solution.

**Comment by rpspringuel** [comment]
Just discovered an interesting quirk: `kpse.find_file` appears capable of traversing directories with spaces in the name while the `\input` statement which actually reads in the gtex file is not.  This results in an interesting bug where the code finds a gtex file which is ready for importing, but cannot actually read it in.  Not sure if this is simply something that needs documenting or some sort of code fix.

**Comment by henryso** [comment]
Is there a way to read a file in a la `\input` which does work with spaces?  If so, then I vote we use it; if not, it's a TeX quirk, and we document it.

**Comment by rpspringuel** [comment]
The best that I can think of is to read in the file in lua using `io.open` and then `tex.sprint` line by line.

**Comment by henryso** [comment]
That seems a bit too much.  My vote is we document it and if there are enough requests for this, then we consider alternatives.

**Comment by eroux** [comment]
I agree with @henryso , let's not "fix TeX"...

**Comment by rpspringuel** [comment]
Okay, this now appears to be complete and behaving the way I want it to.  Please check it carefully as I cannot currently check the kpse search in the test repository.

**Comment by henryso** [comment]
I *don't* think my review is good enough to fully accept this, but it looks OK to me.

**Comment by henryso** [comment]
This has been sitting here for a while with no comments to the contrary, so let's merge.

**Pull request merged**
