### PR TITLE
Documentation Improvement

### PR DESCRIPTION
**Pull request by eschwab**
WIP: addressing #29 

No need to merge right away. This seems like the best way to make this work easily accessible to all. Comments and suggestions are most welcome.

### CODE REVIEW

**Comment by rpspringuel** [comment]
Looks good so far.  Couple of things I noticed (and which are my fault, not yours):

1. There's some inconsistency in how some of the listing of the argument descriptions.  Ones I added earlier in the process look more like sentences (see `\commentary`), while the ones I added later use a more standardized listing format (see `\settranslationcenteringscheme`).  Now that I see a typeset version, I think this should be consistent.
2. Some text indicating what the color definitions at the end of those entries are is probably in order.  Their confusing just tacked on like I left them.

Also, I've added your repository as a remote on my system so that I can pull your changes into my repository, even if this doesn't get merged into the master.  That way when I get a chance to go back to work (probably this weekend) I can add directly to these files, making it less likely that both of us will have to cover the same ground again as this heads towards prime time.

**Comment by eschwab** [comment]
That should resolve point 1. Any comments before I take on the other two files?

**Comment by rpspringuel** [comment]
Looking very nice.

With the other two files (and perhaps with this one, though I'm not as sure), you might want to think of a way to incorporate the file identifiers into the presentation (i.e. pointers to the file where a function is defined).  Right now they're comments, and thus don't show up in the typeset document, but that's mostly because I couldn't figure out what to do with them.  A regular user doesn't really need to know where particular functions are defined, but that information can be very useful to a developer looking to solve a bug or implement a new feature.  Recording the information as comments was my way of keeping track of it while I figured out how to present it.

**Comment by eschwab** [comment]
Finished with Command_Index_gregorio. Would be fairly easy to add the source file pointers to Index_user. I think I will just for consistency.

**Comment by rpspringuel** [comment]
With the first draft done, I'm going to merge this into the main repository if there are no objections.  That should keep the commit history a bit cleaner when I get back to my work.

**Comment by eschwab** [comment]
None from me. I was just sitting on making the request pondering making some further changes/additions, but now it a good breaking point.

**Pull request merged**
