### PR TITLE
Vary filename for scores in scribus render frames

### PR DESCRIPTION
**Pull request by rpspringuel**
Addresses #1588 

@domoknight please test to see if this works.  None of the developers regularly use Scribus so it's difficult for us to test this sort of thing.

### CODE REVIEW

**Comment by domoknight** [comment]
I get the following message multiple times, and no gabc file is generated:

> (c:/texlive/2022/texmf-dist/tex/latex/libertine/LKey.tex))
> ! Undefined control sequence.
> <argument> filec@ntents@checkdir C:Users 
>                               Admin AppData Local Temp scribus _temp_render_hg
> l.11 ...\Temp\scribus_temp_render_hg3448-score.gabc}

**Comment by rpspringuel** [comment]
So, the `$scribus_file$`s are full path filenames, which on a windows system includes "\" which messes with TeX's ability to process the filename (as something like `\Users` gets interpreted as a macro and TeX tries to expand it).  Based on what I can find, I don't think Scribus provides a shorter filename without the path, so let's try a different route: `\jobname`.  I've pushed a change that tries to name the score file using `\jobname` instead of `$scribus_file$`.  Please try this and let me know if it works.

**Comment by domoknight** [comment]
Thank you so much! That appears to have fixed it!

Here are the files I see generated in the Temp dir:
image


And here is the resulting page in Scribus:
image

**Comment by rpspringuel** [comment]
Excellent. Merging. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
