### PR TITLE
Fix for #144

### PR DESCRIPTION
**Pull request by henryso**
This fix for #144 does delete PopulusSion.tex.  If you disagree, I will re-do.

### CODE REVIEW

**Comment by eschwab** [comment]
Dropping `PopulusSion.tex` is consistent with the decision to drop compiled files i.e. `.ttf`, `.pdf`.

**Comment by rpspringuel** [comment]
Should there be a `.tex` file to go with `completetest.gabc` and `test_all_headers.gabc`?

**Comment by eroux** [comment]
@rpspringuel I think these belong to the test/ directory or even better to https://github.com/gregorio-project/gregorio-test

**Comment by rpspringuel** [comment]
Good point.

**Pull request merged**
