### PR TITLE
Improve spacings

### PR DESCRIPTION
**Pull request by eroux**
This is quite a heavy change. The algorithm to compute the space between syllables and between words is completely changed. Now it's globally a constraint system made to respect a minimal distance between letters of the different words and between notes of the different syllables or words. This is also much better documented, and maintainable.

This also fixes a bug present in Gregorio for a very long time: #221 

This change is quite heavy and will certainly break all graphical tests...

### CODE REVIEW

**Comment by henryso** [comment]
I can run these through the tests, but I cannot say for certain whether one result is better than the other, only that they are different.  How do you want me to handle this?  Just accept all the output as correct?  Or should I look for certain things to point out?

**Comment by eroux** [comment]
The best would be to spot really odd output that really shouldn't appear, if something is different but kind of normal, then we can keep it...

**Comment by henryso** [comment]
I am getting some errors:

###### gabc-output/glyphs/bars.gabc
```
! Undefined control sequence.
\greendafterbar ...e@skip@interwordspacetextnotes 
                                                  \grehskip \gre@skip@temp@f...
l.9 }
   %
? 
! Emergency stop.
```

###### gabc-output/glyphs/clef_change.gabc
```
! Improper discretionary list.
\grediscretionary ...x \kern \gre@skip@temp@four }
                                                  {\global \grelastoflinecou...
l.33 }
    %
? 
! Emergency stop.
```

###### gabc-output/glyphs/divisio_finalis.gabc
```
! Undefined control sequence.
\greendafterbar ...e@skip@interwordspacetextnotes 
                                                  \grehskip \gre@skip@temp@f...
l.14 }
    %
? 
! Emergency stop.
```

###### gabc-output/bugs/fix-243.gabc
! Undefined control sequence.
\grebarsyllable ...e@skip@interwordspacetextnotes 
                                                  \hskip \gre@skip@temp@one ...
l.20 }
    %
? 
! Emergency stop.
```

###### tex-output/translation/translation.tex
```
! Undefined control sequence.
\gre@changedimenfactor ...cale@intersyllablespace 
                                                  =1\relax \gre@changeonedim...
l.10 \setgrefactor{15}
                    
? 
! Emergency stop.
```

###### tex-output/sample/sample.tex
```
! Undefined control sequence.
\gre@changedimenfactor ...cale@intersyllablespace 
                                                  =1\relax \gre@changeonedim...
l.10 \setgrefactor{15}
                    
? 
! Emergency stop.
```

###### tex-output/sign-styles/sign-styles.tex
```
! Improper discretionary list.
\grediscretionary ...x \kern \gre@skip@temp@four }
                                                  {\global \grelastoflinecou...
l.30 }
    %
? 
```

**Comment by henryso** [comment]
Of the tests that didn't fail outright, nothing looks particularly weird.  Spacing is stretched out in some cases and made tighter in others.  On a more subjective note, the spacing of words in a line is generally more pleasant to my eye.

**Comment by eroux** [comment]
Should be better now...

**Comment by henryso** [comment]
Ah, the infamous `bars.gabc`.  I have no idea if what it produces is correct, but it sort of looks like the old one, so I guess it's correct?

In any case, other than the spacing changes, I think this now looks fine.  All current tests pass given the conditions laid forth above.

**Comment by eroux** [comment]
Great! This really is a huge step forward! Now the same kind of thing has to be done for bar syllables (which is a bit trickier, but should be relatively similar), but that will be for another PR...

**Pull request merged**
