### PR TITLE
More pylint cleanups.

### PR DESCRIPTION
**Pull request by eschwab**
More could be done to `gregoria2gregorio.py` but with the changes in #292 this script will be in need of updating.

### CODE REVIEW

**Comment by henryso** [comment]
I think we should consider removing gregoria support. As it is, it won't work; there's stuff commented out in the C code.

**Comment by eroux** [comment]
Indeed, it can be removed. I think I'll contact the gregoria creator one of these days, to see if a true integration is possible.

**Comment by eroux** [comment]
@rpspringuel would that be ok to you if the copyright statement in `convertsfdtottf.py` is updated to have the same value as other files?

**Comment by rpspringuel** [comment]
No problem on changing the copyright statement.

**Comment by eschwab** [comment]
Should I remove `gregoria` here or in a separate PR?

**Comment by eroux** [comment]
You can remove it here, I'll merge afterwards

**Comment by eschwab** [comment]
I think I got all the references to `Gregoria`.

**Comment by eroux** [comment]
Thanx a lot !

**Pull request merged**
