### PR TITLE
Improving the handling of the first syllable.

### PR DESCRIPTION
**Pull request by henryso**
This adds a warning when the initial is styled, addressing #247.

In attempting to add the warning, I found some issues with centering of the first syllable.  These are also fixed in this pull request.

These changes pass all the current tests, which obviously don't yet include tests that evoke the centering problem.  I will add these within the next few days.

### CODE REVIEW

**Comment by henryso** [comment]
In creating tests, I found an issue when there's a styled initial vowel.  I will work on this later tonight.

**Comment by henryso** [comment]
At this point, I'm satisfied with the first syllable handling.  Tests have been created in https://github.com/gregorio-project/gregorio-test

**Comment by eroux** [comment]
That's very brave of yours! Don't forget the changelog too, also, I cannot find the tests in the test repo, where are they? Once you've added the changelog entry, you can merge (if tests are present, pull request merging can be quite fast)

**Comment by henryso** [comment]
It would have helped if I had pushed the tests to github.  They are there now in `tests/gabc-dump/first_syllable`.

**Comment by henryso** [comment]
These changes are additional bug fixes for the line item about first syllables already in the change log.

**Comment by eroux** [comment]
Thank you very much, the tests are really great!

**Pull request merged**
