### PR TITLE
Annotation fixes

### PR DESCRIPTION
**Pull request by henryso**
Fixes identified by @rpspringuel for #508.

### CODE REVIEW

**Comment by henryso** [comment]
@rpspringuel Please review and merge if I got your fix right.  Otherwise, let me know what I missed.

**Comment by henryso** [comment]
@rpspringuel I merged 27cfabb83f8bb8a8ead147e0b1ebd55112c56b20.

**Comment by rpspringuel** [comment]
This is good for me then.

You might want to add the sample from the original issue to the tests.

**Comment by henryso** [comment]
Yes, I have new and updated tests staged for this, but I won't be able to get to updating them until later tonight.  Thanks!

**Pull request merged**
