### PR TITLE
Reach the translation glyph node by traverse_id()

### LINKED ISSUE #1180: Translation centering with [/] fails to work when LuaTeX-ja is loaded
Hi!

Sorry, it is me again with yet another LuaTeX-ja related issue, this time with centered translation with `[/]`.  To test, I added a translation for one word in PopulusSion.gabc in the gregorio-test/tests/plain-tex/luatex-ja directory:

```diff
--- a/tests/tex-output/PopulusSion/PopulusSion.gabc
+++ b/tests/tex-output/PopulusSion/PopulusSion.gabc
@@ -17,7 +17,7 @@ style: modern;
 
 % The syntax in this part is called gabc. Please refer to http://home.gna.org/gregorio/gabc/#basis
 
-Pó(c3eh)pu(g)lus(h) Si(hi)on,(hgh.) *(;) ec(hihi)ce(e.) Dó(e.f!gwhhi)mi(h){n}us(h) vé(hi)ni(ig//ih)et(h.) (,) ad(iv./hig) sal(fe)ván(ghg)das(fg) gen(e_f_e_)tes(e.) :(:)
+Pó[People](c3eh)pu(g)lus[/](h) Si(hi)on,(hgh.) *(;) ec(hihi)ce(e.) Dó(e.f!gwhhi)mi(h){n}us(h) vé(hi)ni(ig//ih)et(h.) (,) ad(iv./hig) sal(fe)ván(ghg)das(fg) gen(e_f_e_)tes(e.) :(:)
 
 et(e) au(eh)dí(hhi)tam(i) fá(kjki)ci(i)et(i) Dó(ij)mi(ihi)nus(iv./hiHF) (,) gló(h!i'j)ri(ji!kvJI)am(ij) vo(j.i!jwk)cis(ji) su(i_j_i_)æ,(i.) (;) in(e) læ(e)tí(e!f'h)ti(h)a(hi!jVji)
```

`luatex PopulusSion.tex` runs fine until near the end:

```
(./PopulusSion-4_1_4.gtexerror: ...exlive/texmf-dist/tex/luatex/gregoriotex/gregoriotex.lua:325: attempt to index field 'head' (a nil value)
.
\GreEndScore ...re@localrightbox {}\fi \hfil \par 
                                                  \ifgre@keeprightbox \globa...

l.725 \GreEndScore
                 %
? 
) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}])
Module gregoriotex Warning: Line heights or variable brace lengths may have cha
nged. Rerun to fix. on input line 0
</usr/share/texlive/texmf-dist/fonts/truety
pe/public/gregoriotex/greextra.ttf><../../../fonts/Alegreya-Regular.otf>{/usr/s
hare/texlive/texmf-dist/fonts/enc/dvips/base/8r.enc}</usr/share/texlive/texmf-d
ist/fonts/truetype/public/gregoriotex/greciliae.ttf></usr/share/fonts/truetype/
fonts-japanese-mincho.ttf></usr/share/texlive/texmf-dist/fonts/type1/public/ams
fonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/c
m/cmti10.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/ncntrsbk/uncr8a.pfb
>
Output written on PopulusSion.pdf (1 page, 137324 bytes).
Transcript written on PopulusSion.log.
```

So, a PDF file is generated, except that the translation is not centered.  No big deal though, as I can generate the desired output (Salve Regina, simple tone, with Chinese translation underneath) without LuaTeX-ja, so no hurries.  :-)

Tested with Gregorio 4.1.4 that is included in TeX Live 2016 update.  I haven't tried it with the Gregorio 4.2 branch yet.

Many thanks!

Anthony

### PR DESCRIPTION
**Pull request by anthonyfok**
LuaTeX-ja prepends custom whatsit nodes to store e.g. text direction,
breaking hard-coded paths like startnode.head.next.head.next.head
in the center_translation() function.

This patch uses node.travese_id() to find our desired nodes instead.

Fixes #1180

### CODE REVIEW

**Comment by eroux** [comment]
Looks good to me apart from two things:

- the pull request should be against develop
- did you run the tests on the gregorio-test repository?

**Comment by eroux** [comment]
Oh, also an entry should be added in the CHANGELOG.md file

**Comment by rpspringuel** [comment]
Actually, I think this is a valid candidate for a bug-fix to 4.1.  It fixes a broken feature and only affects the files which are uploaded to CTAN, meaning we can push the update to TeXLive 2016 users who update via `tlmgr`.

It still does need a CHANGELOG.md entry.

**Comment by anthonyfok** [comment]
@eroux Thank you for your review.  I am sorry that I had been very busy and still haven't found the time too follow up, especially in providing test cases in the gregorio-tests repository.

@rpspringuel Thank you so much for merging this pull request.  Unfortunately, I encountered a bug Saturday afternoon when I tried to change the Chinese font used in the translation, using `\setmainjfont` from `luatexja-fontspec`, `lualatex` crashed with this error:

```
! error:  (node lib): lua <node> expected, not an object with type nil
```

It crashed here:

```lua
  local trans_width = node.dimensions(glyphnode)
```

because `glyphnode` becomes `nil` with certain fonts, for reasons that still befuddles me.  (I know too little about TeX.)  Anyhow, my patch has wrongly assumed that the translation text would be enclosed in the glyph node directly within the hbox, as in `vlist { hlist { glyph }}`.  It turns out that, with some CJK fonts, the glyph node got wrapped into one deeper level, as in `vlist { hlist { hlist { glyph } } }`.

"Good fonts" that work: "Adobe Ming Std", "Adobe Song Std", "AR PL UKai TW", "AR PL UMing TW", where a dump_nodes() would show this:

```
Module gregoriotex Info: node hlist [2] {1} on input line 63
Module gregoriotex Info: ..node whatsit [8] {1} on input line 63
Module gregoriotex Info: ..node rule [3] {1} on input line 63
Module gregoriotex Info: ..node glyph [256] {1} on input line 63
Module gregoriotex Info: ..node glue [13] {1} on input line 63
Module gregoriotex Info: ..node rule [3] {1} on input line 63
Module gregoriotex Info: ..node glyph [256] {1} on input line 63
Module gregoriotex Info: ..penalty=10000 {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node hlist [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: --end dump-- on input line 63
```

"Bad fonts" that would crash: STZhongSong, Fandol, cwTeXKai, HanWangMingBold etc.

```
Module gregoriotex Info: node hlist [2] {1} on input line 63
Module gregoriotex Info: ..node whatsit [8] {1} on input line 63
Module gregoriotex Info: ..node hlist [0] {1} on input line 63
Module gregoriotex Info: ..node glue [13] {1} on input line 63
Module gregoriotex Info: ..node hlist [0] {1} on input line 63
Module gregoriotex Info: ..penalty=10000 {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node hlist [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: ..node glue [0] {1} on input line 63
Module gregoriotex Info: --end dump-- on input line 63
```

So, my quick fix is to check for `nil` right after the `local glyphnode = get_first_node_by_id(glyph, hlistnode.head)` line:

```lua
  if glyphnode == nil then
      glyphnode = get_first_node_by_id(hlist, hlistnode.head)
  end
```

Though probably it shouldn't be called a `glyphnode` any more.  This, fortunately, fixes the crash.  For example, cwTeXKai and Fandol works perfectly after this patch.

However, with STZhongSong and HanWangMingBold, there are the occasional translation text that are not quite centered but somehow shifted to the right.  But that is a relatively minor issue that shouldn't hold up 4.1.5.

So, @rpspringuel, would you like me to make a new pull request adding the check for `nil`?  Or would you like to do this yourself (and probably with a better fix)?  Please let me know.  Many thanks!

(I will be at the computer this morning standing by.  I will also try to upload my test files somewhere if you would like to take a look at them.)

Thanks again!

**Comment by anthonyfok** [comment]
Oops, I see that I am too late (4.1.5 is out, yay!)  No worries.  Maybe for 4.1.6 then.  I will make another pull request when I make progress (i.e. when the alignment is correct for all fonts.)

Thank you all!

**Comment by rpspringuel** [comment]
Please do.  Just be sure to submit a new PR against the `ctan` branch, not `master`.

**Comment by anthonyfok** [comment]
@rpspringuel Thank you for the note about the `ctan` branch, otherwise I would have incorrectly submitted the PR against `master` again.   :wink:

And thank you to you all, all Gregorio authors, for making typesetting Gregorian chant possible on the computer!  Here is Salve Regina with Chinese translation (not the official Chinese translation; it has been modified to try to fit the Latin text order while kind of making sense in Chinese, but hopefully can help our choir and parishioners learn it):

[Salve_Regina_中文譯詞.pdf](https://github.com/gregorio-project/gregorio/files/430533/Salve_Regina_.pdf)

salve_regina_projector-p1
salve_regina_projector-p2
salve_regina_projector-p3

**Pull request merged**
