### PR TITLE
Fix 905 - Add linebreaks to gabc output.

### PR DESCRIPTION
**Pull request by eschwab**
Addresses  #905 

Ready for review.

### CODE REVIEW

**Comment by rpspringuel** [comment]
I strongly suspect that this breaks the gabc-gabc tests.  Have you checked that?

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eschwab** [comment]
I have attempted to test that, and the `gabc-gabc` tests pass. I have not dug deep into it yet, since I expected at least one to fail.

**Comment by henryso** [comment]
You might be doing something wrong.  On my system, pretty much all gabc-gabc tests (expectedly) fail under your branch.

**Comment by eschwab** [comment]
I can't figure out I am doing wrong. `./gregorio-test.sh gabc-gabc` reports that all pass with a real time of `.055s`. Changing the option to `gabc-output` has the same result.

**Comment by henryso** [comment]
Did you install the new gregorio?  If not, you need to use the -g argument to point at your build directory.

**Comment by eschwab** [comment]
Yes, the new gregorio is installed. `$(which gregorio) -V` gives the correct version.

**Comment by henryso** [comment]
Looking at your command again, `./gregorio-test.sh gabc-gabc` will not run any tests.  You should instead use `./gregorio-test.sh tests/gabc-gabc/**/*.gabc` (in bash, you'll have to set the `globstar` shell option):
```
shopt -s globstar
./gregorio-test.sh tests/gabc-gabc/**/*.gabc
```

**Comment by eschwab** [comment]
Ok, I think I have it figured out now. There should be a PR to the test repo for this one.

**Comment by eroux** [comment]
Tests and code are ok for me to merge

**Pull request merged**
