### PR TITLE
Simpler fix for filenames

### PR DESCRIPTION
**Pull request by rpspringuel**
This fix for problematic filenames seems to work and is simpler than what I was working on in #1426.
It is compatible with gregorio-project/gregorio-test#328 after the changes I proposed on henryso/gregorio-test#1 are pulled in.
The corresponding PR which adds the test for this problem is gregorio-project/gregorio-test#331

If this is approved, #1426 can be closed without merging.

### CODE REVIEW

**Comment by henryso** [comment]
As long as this works on Windows, I'm OK with it.

**Comment by rpspringuel** [comment]
I haven't checked that yet.  Thanks for the reminder.

**Comment by rpspringuel** [comment]
Found an issue here.  Quoting the executable name fouls up the security restrictions:  `gregorio` is an allowed executable, but `"gregorio"` is not (when `shell_escape=p`).  I'm going to need to change that up and do some more testing.

**Comment by henryso** [comment]
Maybe just remove the escaping of the executable and document that gregorio shouldn't be installed in a directory with a space in it?

**Comment by rpspringuel** [comment]
Well, the executable never gets called with its full path anyway.  We rely on it being in `PATH`.  So I think just removing the quotes around it should be sufficient. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rpspringuel** [comment]
Just tested on Windows (with f0b263) and stuff seems to be working fine.

**Comment by rpspringuel** [comment]
TeX Live is looking to freeze the Pretest as soon as Monday.  I'm planning to merge #1448 over the weekend to make sure that fix is in TeX Live 2019.  Does anyone think this should be merged too?

**Comment by henryso** [comment]
I think we should go ahead with this.

**Pull request merged**
