### PR TITLE
Fix 1029

### PR DESCRIPTION
**Pull request by rpspringuel**
A somewhat working attempt to make things line up.  There are some quirks still that I'm not quite sure what to do with.  They're small enough, however, that could probably be neglected for now.  Rather than tell you what they are, I'd like to see if others can spot them as if you can, that clearly indicates that they need to be fixed.

### CODE REVIEW

**Comment by henryso** [comment]
I hope you don't mean that comment towards me, because I don't really grok the spacing algorithms and all the underlying spaces and how they are composed to make the system produce what it does.

**Comment by rpspringuel** [comment]
Actually, I don't expect anyone to spot the problems in the code (though if anyone can, that would be nice).  Rather I'm looking for people to examine the test results and visually decide if they are "right" or not.  I can spot the "problems" because I've been looking at the results with the barspacing and notespacing markers, but they're fairly small and so I'm not sure that someone approaching an unmarked score with fresh eyes will even be able to spot them.  If no one sees them, then I think it's reasonable to accept this as is and wait for some use case to crop up in which those small problems become unacceptably large before spending more time trying to quash them.

**Comment by henryso** [comment]
On that front, I personally think that we should look at the output, and if it looks reasonable (i.e., not bad or good enough) then it's fine.  Given my position on that, the output looks fine.  I cannot definitively or even subjectively say that the difference is "worse" or "better" than before.

**Comment by eroux** [comment]
The code looks simple enough, I think this can be merged, thanks a lot!

**Pull request merged**
