### PR TITLE
General clean-up of the C code.

### PR DESCRIPTION
**Pull request by henryso**
I converted a few more defines to enums and did a general pass through the code to remove unnecessary global symbols (leaving them static in their files).  I also found some dead code and removed it.  The diff is pretty difficult to read because I re-arranged the functions as I removed the declarations from the header file.  However, the tests all pass, so I'm pretty confident I didn't break anything.

### CODE REVIEW

**Comment by henryso** [comment]
Any objections to this refactoring?  If not, I will commit later tonight.

**Comment by eschwab** [comment]
Looks fine to me.

**Comment by rpspringuel** [comment]
I haven't had a chance to test, but if you guys say it's okay, go ahead.

**Comment by henryso** [comment]
I meant objections on a philosophical level, but there don't seem to be, so I'll merge this.

**Pull request merged**
