### PR TITLE
add Metadata (and icon) to windows executable

### LINKED ISSUE #69: Add Windows Metadata to gregorio.exe
See [this post](https://www.mail-archive.com/gregorio-users@gna.org/msg02312.html) for the request, and [this](http://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable) and [that](http://gnu-automake.7480.n7.nabble.com/correct-windres-use-td4889.html) for hints.

Also, the icon could be added to the main `.exe` file, with the same process.

Low priority.

### PR DESCRIPTION
**Pull request by eroux**
This fixes #69 and also updates VERSION (more to come on this)

### CODE REVIEW

**Comment by eroux** [comment]
I admit I don't understand why it cannot be merged automatically... if someone gives me a go, I'll merge it by hand.

**Comment by henryso** [comment]
As far as I can tell, it's because of a conflict in VersionUpdate.py.  Both parents have changed this file.

```
<<<<<<< HEAD
            result.append(re.sub(r'[\d.]+-?\w*', newver, line))
=======
            result.append(re.sub(r'[0-9.]+', newver, line))
        elif re.search(r'FileVersion', line):
            result.append(re.sub(r'[0-9.]+', newver, line))
>>>>>>> 9d6019dc62a2a60052822f55f156138c99f14fb7
```

**Comment by rpspringuel** [comment]
The version number has already had this update applied in #92.  Perhaps you're branching from before the merge?

**Comment by eroux** [comment]
yes, I'm trying to fix that... but it seems I broke it more... I'll just make a brand new pull request soon.

**Comment by eroux** [comment]
replaced by #116

**Pull request closed without merging**
