### PR TITLE
CTAN related fixes/upgrades

### PR DESCRIPTION
**Pull request by rpspringuel**
The original commit is so that `make maintainer-clean` will remove `gregoriotex.ctan.zip` if it is present.

### CODE REVIEW

**Comment by rpspringuel** [comment]
Rather than open a new PR, I'm adding some other CTAN related changes to this one.  I expect that I'll release 5.1.1 shortly after those changes are made (even though, so far at least, they are purely developer or documentation changes).

**Comment by rpspringuel** [comment]
Just addressed #1405 in the simplest possible manner by adding the folder name to the name of the file too.  That is `fonts/README.md` -> `fonts/fonts_README.md` etc.  Let me know if this isn't an acceptable solution.

**Comment by rpspringuel** [comment]
Modifications to VersionManager to address #1403 have now been uploaded.

**Comment by henryso** [comment]
This looks OK to me.  I'd merge it, but I don't know if you're done.

**Comment by rpspringuel** [comment]
Looking at the issues I've assigned to 5.1.1, there's only #1406 and #1362 to deal with.  @eschwab has assigned a separate PR in #1411 for the former, the latter though no one has touched yet.  Given the additional work involved in that issue, it probably makes sense to give it its own PR, so I would say this is ready for merge.

**Comment by rpspringuel** [comment]
In reviewing #1411 I found a couple other files which I think that `make maintainer-clean` ought to remove.  Please take a look and confirm.

**Comment by henryso** [comment]
I think it's fine for maintainer-clean to clean those.  Just make sure that distcheck, et al, still work correctly.

**Comment by rpspringuel** [comment]
Thanks for pointing that out.  When I ran `make distcheck` and `make ctan` I found a couple problems that I've now fixed (and tried to generalize them to fix all targets at the same time).  I think I've checked all the primary targets now, but may have missed some of the more obscure ones (being less familiar with make than some).  If you have a list of particular targets that you'd like checked, please let me know.

**Comment by rpspringuel** [comment]
Okay, I could probably continue to piddle around with this forever so I'm going to force myself to stop here.  If there are no objections, I'll merge this on Saturday and then will start working on the 5.1.1 release on Sunday or when #1411 is merged (which ever comes second).

**Pull request merged**
