### PR TITLE
Cavum glyphs

### PR DESCRIPTION
**Pull request by henryso**
Implemented expanded set of cavum glyphs (#844).

Note: this is a seriously big and potentially breaking pull request and should not be pulled into 4.2.

Tests obviously change because of this.

Please review and merge if satisfactory.

### CODE REVIEW

**Comment by eroux** [comment]
Thanks, that's quite impressive! I'll review it tonight

**Comment by eroux** [comment]
I'm getting a warning in this branch, but it may come from another PR:

```
struct.c: In function ‘gregorio_change_shape’:
struct.c:380:20: warning: variable ‘old_shape’ set but not used [-Wunused-but-set-variable]
     gregorio_shape old_shape;
```

**Comment by eroux** [comment]
Well, apart from this tiny warning everything looks really perfect! Thank you very much for this, I think this is a great feature that will allow gregorian chant typography to go one step further. Ok for me to be merged (with or without the fix for the warning, it can be for another PR)

**Comment by henryso** [comment]
It's most likely from here.  The cavum changes reduced a lot of "special" glyph transformation code.  I will try to fix it tonight and add the tests you requested.

**Comment by henryso** [comment]
I made the changes and added the tests.  Please review at your leisure.

**Comment by eroux** [comment]
Perfect, thanks a lot!

**Pull request merged**
