### PR TITLE
Fixes for 862, 863, 880, and 903.

### LINKED ISSUE #862: Heuristics should include notes that are "glued" to the glyph
From https://github.com/gregorio-project/gregorio/issues/803#issuecomment-178697013:

The heuristics to know if a ledger line is present or not under the glyph should also check the notes glued to the current glyph, for instance `b!dv` should have a long form by default. I think notes separated by a `/0` space should be counted too

### PR DESCRIPTION
**Pull request by henryso**
Fixes #862, #863, #880, and #903.

This also fixes a bug found in the #901.

I updated tests as necessary.

Please review and merge if satisfactory.  If you'd rather I split this into multiple pull requests, I can do that as well.

### CODE REVIEW

**Comment by rpspringuel** [comment]
It may be that #862 and #863 are refinements of new features in 4.1 and thus their CHANGELOG entries will eventually be consolidated away, but since these affect the visual output, I'm inclined to mention them in the CHANGELOG, at least during the release process.

**Comment by rpspringuel** [comment]
I'm getting a test failure for this.

gabc-gabc/glyphs/horizontal_episema_tuning.gabc has two extra `[lh:m{]` in the output.  It appears that they are being repeated at the start of the subsequent syllable when the defined range spans multiple syllables.

**Comment by henryso** [comment]
I thought that we only add CHANGELOG entries for that kind of thing after rc1 and not through the betas, but I'll add it since you feel that strongly about it.  I'll also the problem you noticed with the gabc-gabc test.

**Comment by rpspringuel** [comment]
Another test failure.

It seems the new results from the bar-spacing-old test (i.e. the ones with the translation examples) didn't get merged in properly.  Can you simply accept the results for this test to fix that here?

**Comment by henryso** [comment]
I'm not getting these test failures.  Maybe there's something wrong with my test directory.

**Comment by henryso** [comment]
Regarding gabc-gabc/glyphs/horizontal_episema_tuning.gabc, are you saying it doesn't match the expectation or that the expectation is, in your opinion, wrong?

I noticed that gabc output was using the old letters (`lh` instead of `uh`), so I've fixed that, but otherwise, the expectation looks correct to me.

**Comment by henryso** [comment]
I think I found the problem that you are seeing in the gabc-gabc test.  Valgrind found uninitialized variable usage, so that might be causing the problem.  I will have a fix up shortly.

**Comment by henryso** [comment]
I believe I've addressed all the issues here, and I've rerun the coverage test and the valgrind/sanitize tests and corrected the issues they found.

Please review the result.

**Comment by eroux** [comment]
Wonderful! Thank you very much for this, that will make the issue tracker lighter! The only thing left I see is documenting it in Gabc.tex, but let's keep it for another PR

**Pull request merged**
